/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.AccountInput
import com.google.gerrit.client.model.AuthTokenInput

class AccountInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountInput
        //val modelInstance = AccountInput()

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `sshKey`
        should("test sshKey") {
            // uncomment below to test the property
            //modelInstance.sshKey shouldBe ("TODO")
        }

        // to test the property `httpPassword`
        should("test httpPassword") {
            // uncomment below to test the property
            //modelInstance.httpPassword shouldBe ("TODO")
        }

        // to test the property `tokens`
        should("test tokens") {
            // uncomment below to test the property
            //modelInstance.tokens shouldBe ("TODO")
        }

        // to test the property `groups`
        should("test groups") {
            // uncomment below to test the property
            //modelInstance.groups shouldBe ("TODO")
        }

    }
}
