/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.AvatarInfo

class AccountInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountInfo
        //val modelInstance = AccountInfo()

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `secondaryEmails`
        should("test secondaryEmails") {
            // uncomment below to test the property
            //modelInstance.secondaryEmails shouldBe ("TODO")
        }

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `avatars`
        should("test avatars") {
            // uncomment below to test the property
            //modelInstance.avatars shouldBe ("TODO")
        }

        // to test the property `moreAccounts`
        should("test moreAccounts") {
            // uncomment below to test the property
            //modelInstance.moreAccounts shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `inactive`
        should("test inactive") {
            // uncomment below to test the property
            //modelInstance.inactive shouldBe ("TODO")
        }

        // to test the property `deleted`
        should("test deleted") {
            // uncomment below to test the property
            //modelInstance.deleted shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
