/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.AddMembersInput

class AddMembersInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddMembersInput
        //val modelInstance = AddMembersInput()

        // to test the property `oneMember`
        should("test oneMember") {
            // uncomment below to test the property
            //modelInstance.oneMember shouldBe ("TODO")
        }

        // to test the property `members`
        should("test members") {
            // uncomment below to test the property
            //modelInstance.members shouldBe ("TODO")
        }

    }
}
