/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ApplyProvidedFixInput
import com.google.gerrit.client.model.FixReplacementInfo

class ApplyProvidedFixInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApplyProvidedFixInput
        //val modelInstance = ApplyProvidedFixInput()

        // to test the property `fixReplacementInfos`
        should("test fixReplacementInfos") {
            // uncomment below to test the property
            //modelInstance.fixReplacementInfos shouldBe ("TODO")
        }

        // to test the property `originalPatchsetForFix`
        should("test originalPatchsetForFix") {
            // uncomment below to test the property
            //modelInstance.originalPatchsetForFix shouldBe ("TODO")
        }

    }
}
