/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.AuthInfo
import com.google.gerrit.client.model.AccountFieldName
import com.google.gerrit.client.model.AgreementInfo
import com.google.gerrit.client.model.AuthType
import com.google.gerrit.client.model.GitBasicAuthPolicy

class AuthInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthInfo
        //val modelInstance = AuthInfo()

        // to test the property `authType`
        should("test authType") {
            // uncomment below to test the property
            //modelInstance.authType shouldBe ("TODO")
        }

        // to test the property `useContributorAgreements`
        should("test useContributorAgreements") {
            // uncomment below to test the property
            //modelInstance.useContributorAgreements shouldBe ("TODO")
        }

        // to test the property `contributorAgreements`
        should("test contributorAgreements") {
            // uncomment below to test the property
            //modelInstance.contributorAgreements shouldBe ("TODO")
        }

        // to test the property `editableAccountFields`
        should("test editableAccountFields") {
            // uncomment below to test the property
            //modelInstance.editableAccountFields shouldBe ("TODO")
        }

        // to test the property `loginUrl`
        should("test loginUrl") {
            // uncomment below to test the property
            //modelInstance.loginUrl shouldBe ("TODO")
        }

        // to test the property `loginText`
        should("test loginText") {
            // uncomment below to test the property
            //modelInstance.loginText shouldBe ("TODO")
        }

        // to test the property `switchAccountUrl`
        should("test switchAccountUrl") {
            // uncomment below to test the property
            //modelInstance.switchAccountUrl shouldBe ("TODO")
        }

        // to test the property `registerUrl`
        should("test registerUrl") {
            // uncomment below to test the property
            //modelInstance.registerUrl shouldBe ("TODO")
        }

        // to test the property `registerText`
        should("test registerText") {
            // uncomment below to test the property
            //modelInstance.registerText shouldBe ("TODO")
        }

        // to test the property `editFullNameUrl`
        should("test editFullNameUrl") {
            // uncomment below to test the property
            //modelInstance.editFullNameUrl shouldBe ("TODO")
        }

        // to test the property `httpPasswordUrl`
        should("test httpPasswordUrl") {
            // uncomment below to test the property
            //modelInstance.httpPasswordUrl shouldBe ("TODO")
        }

        // to test the property `gitBasicAuthPolicy`
        should("test gitBasicAuthPolicy") {
            // uncomment below to test the property
            //modelInstance.gitBasicAuthPolicy shouldBe ("TODO")
        }

        // to test the property `maxTokenLifetime`
        should("test maxTokenLifetime") {
            // uncomment below to test the property
            //modelInstance.maxTokenLifetime shouldBe ("TODO")
        }

    }
}
