/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.AutoCloseableChangesCheckInput

class AutoCloseableChangesCheckInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AutoCloseableChangesCheckInput
        //val modelInstance = AutoCloseableChangesCheckInput()

        // to test the property `fix`
        should("test fix") {
            // uncomment below to test the property
            //modelInstance.fix shouldBe ("TODO")
        }

        // to test the property `branch`
        should("test branch") {
            // uncomment below to test the property
            //modelInstance.branch shouldBe ("TODO")
        }

        // to test the property `skipCommits`
        should("test skipCommits") {
            // uncomment below to test the property
            //modelInstance.skipCommits shouldBe ("TODO")
        }

        // to test the property `maxCommits`
        should("test maxCommits") {
            // uncomment below to test the property
            //modelInstance.maxCommits shouldBe ("TODO")
        }

    }
}
