/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.BanResultInfo

class BanResultInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BanResultInfo
        //val modelInstance = BanResultInfo()

        // to test the property `newlyBanned`
        should("test newlyBanned") {
            // uncomment below to test the property
            //modelInstance.newlyBanned shouldBe ("TODO")
        }

        // to test the property `alreadyBanned`
        should("test alreadyBanned") {
            // uncomment below to test the property
            //modelInstance.alreadyBanned shouldBe ("TODO")
        }

        // to test the property `ignored`
        should("test ignored") {
            // uncomment below to test the property
            //modelInstance.ignored shouldBe ("TODO")
        }

    }
}
