/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.BatchLabelInput
import com.google.gerrit.client.model.LabelDefinitionInput

class BatchLabelInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatchLabelInput
        //val modelInstance = BatchLabelInput()

        // to test the property `commitMessage`
        should("test commitMessage") {
            // uncomment below to test the property
            //modelInstance.commitMessage shouldBe ("TODO")
        }

        // to test the property `delete`
        should("test delete") {
            // uncomment below to test the property
            //modelInstance.delete shouldBe ("TODO")
        }

        // to test the property `create`
        should("test create") {
            // uncomment below to test the property
            //modelInstance.create shouldBe ("TODO")
        }

        // to test the property `update`
        should("test update") {
            // uncomment below to test the property
            //modelInstance.update shouldBe ("TODO")
        }

    }
}
