/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.CherryPickInput
import com.google.gerrit.client.model.NotifyHandling
import com.google.gerrit.client.model.NotifyInfo

class CherryPickInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CherryPickInput
        //val modelInstance = CherryPickInput()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `destination`
        should("test destination") {
            // uncomment below to test the property
            //modelInstance.destination shouldBe ("TODO")
        }

        // to test the property `base`
        should("test base") {
            // uncomment below to test the property
            //modelInstance.base shouldBe ("TODO")
        }

        // to test the property `parent`
        should("test parent") {
            // uncomment below to test the property
            //modelInstance.parent shouldBe ("TODO")
        }

        // to test the property `notify`
        should("test notify") {
            // uncomment below to test the property
            //modelInstance.notify shouldBe ("TODO")
        }

        // to test the property `notifyDetails`
        should("test notifyDetails") {
            // uncomment below to test the property
            //modelInstance.notifyDetails shouldBe ("TODO")
        }

        // to test the property `keepReviewers`
        should("test keepReviewers") {
            // uncomment below to test the property
            //modelInstance.keepReviewers shouldBe ("TODO")
        }

        // to test the property `allowConflicts`
        should("test allowConflicts") {
            // uncomment below to test the property
            //modelInstance.allowConflicts shouldBe ("TODO")
        }

        // to test the property `topic`
        should("test topic") {
            // uncomment below to test the property
            //modelInstance.topic shouldBe ("TODO")
        }

        // to test the property `allowEmpty`
        should("test allowEmpty") {
            // uncomment below to test the property
            //modelInstance.allowEmpty shouldBe ("TODO")
        }

        // to test the property `validationOptions`
        should("test validationOptions") {
            // uncomment below to test the property
            //modelInstance.validationOptions shouldBe ("TODO")
        }

        // to test the property `committerEmail`
        should("test committerEmail") {
            // uncomment below to test the property
            //modelInstance.committerEmail shouldBe ("TODO")
        }

    }
}
