/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.CleanupChangesInput

class CleanupChangesInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CleanupChangesInput
        //val modelInstance = CleanupChangesInput()

        // to test the property `after`
        should("test after") {
            // uncomment below to test the property
            //modelInstance.after shouldBe ("TODO")
        }

        // to test the property `ifMergeable`
        should("test ifMergeable") {
            // uncomment below to test the property
            //modelInstance.ifMergeable shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `query`
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

    }
}
