/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.CommitInfo
import com.google.gerrit.client.model.GitPerson
import com.google.gerrit.client.model.WebLinkInfo

class CommitInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CommitInfo
        //val modelInstance = CommitInfo()

        // to test the property `commit`
        should("test commit") {
            // uncomment below to test the property
            //modelInstance.commit shouldBe ("TODO")
        }

        // to test the property `parents`
        should("test parents") {
            // uncomment below to test the property
            //modelInstance.parents shouldBe ("TODO")
        }

        // to test the property `author`
        should("test author") {
            // uncomment below to test the property
            //modelInstance.author shouldBe ("TODO")
        }

        // to test the property `committer`
        should("test committer") {
            // uncomment below to test the property
            //modelInstance.committer shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `webLinks`
        should("test webLinks") {
            // uncomment below to test the property
            //modelInstance.webLinks shouldBe ("TODO")
        }

        // to test the property `resolveConflictsWebLinks`
        should("test resolveConflictsWebLinks") {
            // uncomment below to test the property
            //modelInstance.resolveConflictsWebLinks shouldBe ("TODO")
        }

    }
}
