/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.CommonFileInfo

class CommonFileInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CommonFileInfo
        //val modelInstance = CommonFileInfo()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `oldMode`
        should("test oldMode") {
            // uncomment below to test the property
            //modelInstance.oldMode shouldBe ("TODO")
        }

        // to test the property `newMode`
        should("test newMode") {
            // uncomment below to test the property
            //modelInstance.newMode shouldBe ("TODO")
        }

        // to test the property `oldSha`
        should("test oldSha") {
            // uncomment below to test the property
            //modelInstance.oldSha shouldBe ("TODO")
        }

        // to test the property `newSha`
        should("test newSha") {
            // uncomment below to test the property
            //modelInstance.newSha shouldBe ("TODO")
        }

        // to test the property `binary`
        should("test binary") {
            // uncomment below to test the property
            //modelInstance.binary shouldBe ("TODO")
        }

        // to test the property `oldPath`
        should("test oldPath") {
            // uncomment below to test the property
            //modelInstance.oldPath shouldBe ("TODO")
        }

        // to test the property `linesInserted`
        should("test linesInserted") {
            // uncomment below to test the property
            //modelInstance.linesInserted shouldBe ("TODO")
        }

        // to test the property `linesDeleted`
        should("test linesDeleted") {
            // uncomment below to test the property
            //modelInstance.linesDeleted shouldBe ("TODO")
        }

        // to test the property `sizeDelta`
        should("test sizeDelta") {
            // uncomment below to test the property
            //modelInstance.sizeDelta shouldBe ("TODO")
        }

        // to test the property `propertySize`
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `diffsTooExpensiveToCompute`
        should("test diffsTooExpensiveToCompute") {
            // uncomment below to test the property
            //modelInstance.diffsTooExpensiveToCompute shouldBe ("TODO")
        }

    }
}
