/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ConfigParameterInfo
import com.google.gerrit.client.model.ProjectConfigEntryType

class ConfigParameterInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigParameterInfo
        //val modelInstance = ConfigParameterInfo()

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `warning`
        should("test warning") {
            // uncomment below to test the property
            //modelInstance.warning shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `editable`
        should("test editable") {
            // uncomment below to test the property
            //modelInstance.editable shouldBe ("TODO")
        }

        // to test the property `inheritable`
        should("test inheritable") {
            // uncomment below to test the property
            //modelInstance.inheritable shouldBe ("TODO")
        }

        // to test the property `configuredValue`
        should("test configuredValue") {
            // uncomment below to test the property
            //modelInstance.configuredValue shouldBe ("TODO")
        }

        // to test the property `inheritedValue`
        should("test inheritedValue") {
            // uncomment below to test the property
            //modelInstance.inheritedValue shouldBe ("TODO")
        }

        // to test the property `permittedValues`
        should("test permittedValues") {
            // uncomment below to test the property
            //modelInstance.permittedValues shouldBe ("TODO")
        }

        // to test the property `propertyValues`
        should("test propertyValues") {
            // uncomment below to test the property
            //modelInstance.propertyValues shouldBe ("TODO")
        }

    }
}
