/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ConfigInfo
import com.google.gerrit.client.model.ActionInfo
import com.google.gerrit.client.model.CommentLinkInfo
import com.google.gerrit.client.model.ConfigParameterInfo
import com.google.gerrit.client.model.InheritedBooleanInfo
import com.google.gerrit.client.model.MaxObjectSizeLimitInfo
import com.google.gerrit.client.model.ProjectState
import com.google.gerrit.client.model.SubmitType
import com.google.gerrit.client.model.SubmitTypeInfo

class ConfigInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigInfo
        //val modelInstance = ConfigInfo()

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `useContributorAgreements`
        should("test useContributorAgreements") {
            // uncomment below to test the property
            //modelInstance.useContributorAgreements shouldBe ("TODO")
        }

        // to test the property `useContentMerge`
        should("test useContentMerge") {
            // uncomment below to test the property
            //modelInstance.useContentMerge shouldBe ("TODO")
        }

        // to test the property `useSignedOffBy`
        should("test useSignedOffBy") {
            // uncomment below to test the property
            //modelInstance.useSignedOffBy shouldBe ("TODO")
        }

        // to test the property `createNewChangeForAllNotInTarget`
        should("test createNewChangeForAllNotInTarget") {
            // uncomment below to test the property
            //modelInstance.createNewChangeForAllNotInTarget shouldBe ("TODO")
        }

        // to test the property `requireChangeId`
        should("test requireChangeId") {
            // uncomment below to test the property
            //modelInstance.requireChangeId shouldBe ("TODO")
        }

        // to test the property `enableSignedPush`
        should("test enableSignedPush") {
            // uncomment below to test the property
            //modelInstance.enableSignedPush shouldBe ("TODO")
        }

        // to test the property `requireSignedPush`
        should("test requireSignedPush") {
            // uncomment below to test the property
            //modelInstance.requireSignedPush shouldBe ("TODO")
        }

        // to test the property `rejectImplicitMerges`
        should("test rejectImplicitMerges") {
            // uncomment below to test the property
            //modelInstance.rejectImplicitMerges shouldBe ("TODO")
        }

        // to test the property `privateByDefault`
        should("test privateByDefault") {
            // uncomment below to test the property
            //modelInstance.privateByDefault shouldBe ("TODO")
        }

        // to test the property `workInProgressByDefault`
        should("test workInProgressByDefault") {
            // uncomment below to test the property
            //modelInstance.workInProgressByDefault shouldBe ("TODO")
        }

        // to test the property `enableReviewerByEmail`
        should("test enableReviewerByEmail") {
            // uncomment below to test the property
            //modelInstance.enableReviewerByEmail shouldBe ("TODO")
        }

        // to test the property `matchAuthorToCommitterDate`
        should("test matchAuthorToCommitterDate") {
            // uncomment below to test the property
            //modelInstance.matchAuthorToCommitterDate shouldBe ("TODO")
        }

        // to test the property `rejectEmptyCommit`
        should("test rejectEmptyCommit") {
            // uncomment below to test the property
            //modelInstance.rejectEmptyCommit shouldBe ("TODO")
        }

        // to test the property `skipAddingAuthorAndCommitterAsReviewers`
        should("test skipAddingAuthorAndCommitterAsReviewers") {
            // uncomment below to test the property
            //modelInstance.skipAddingAuthorAndCommitterAsReviewers shouldBe ("TODO")
        }

        // to test the property `maxObjectSizeLimit`
        should("test maxObjectSizeLimit") {
            // uncomment below to test the property
            //modelInstance.maxObjectSizeLimit shouldBe ("TODO")
        }

        // to test the property `submitType`
        should("test submitType") {
            // uncomment below to test the property
            //modelInstance.submitType shouldBe ("TODO")
        }

        // to test the property `defaultSubmitType`
        should("test defaultSubmitType") {
            // uncomment below to test the property
            //modelInstance.defaultSubmitType shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `pluginConfig`
        should("test pluginConfig") {
            // uncomment below to test the property
            //modelInstance.pluginConfig shouldBe ("TODO")
        }

        // to test the property `actions`
        should("test actions") {
            // uncomment below to test the property
            //modelInstance.actions shouldBe ("TODO")
        }

        // to test the property `commentlinks`
        should("test commentlinks") {
            // uncomment below to test the property
            //modelInstance.commentlinks shouldBe ("TODO")
        }

        // to test the property `extensionPanelNames`
        should("test extensionPanelNames") {
            // uncomment below to test the property
            //modelInstance.extensionPanelNames shouldBe ("TODO")
        }

    }
}
