/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ConsistencyCheckInput

class ConsistencyCheckInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConsistencyCheckInput
        //val modelInstance = ConsistencyCheckInput()

        // to test the property `checkAccounts`
        should("test checkAccounts") {
            // uncomment below to test the property
            //modelInstance.checkAccounts shouldBe ("TODO")
        }

        // to test the property `checkAccountExternalIds`
        should("test checkAccountExternalIds") {
            // uncomment below to test the property
            //modelInstance.checkAccountExternalIds shouldBe ("TODO")
        }

        // to test the property `checkGroups`
        should("test checkGroups") {
            // uncomment below to test the property
            //modelInstance.checkGroups shouldBe ("TODO")
        }

    }
}
