/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ContentEntry

class ContentEntryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ContentEntry
        //val modelInstance = ContentEntry()

        // to test the property `ab`
        should("test ab") {
            // uncomment below to test the property
            //modelInstance.ab shouldBe ("TODO")
        }

        // to test the property `a`
        should("test a") {
            // uncomment below to test the property
            //modelInstance.a shouldBe ("TODO")
        }

        // to test the property `b`
        should("test b") {
            // uncomment below to test the property
            //modelInstance.b shouldBe ("TODO")
        }

        // to test the property `editA`
        should("test editA") {
            // uncomment below to test the property
            //modelInstance.editA shouldBe ("TODO")
        }

        // to test the property `editB`
        should("test editB") {
            // uncomment below to test the property
            //modelInstance.editB shouldBe ("TODO")
        }

        // to test the property `dueToRebase`
        should("test dueToRebase") {
            // uncomment below to test the property
            //modelInstance.dueToRebase shouldBe ("TODO")
        }

        // to test the property `common`
        should("test common") {
            // uncomment below to test the property
            //modelInstance.common shouldBe ("TODO")
        }

        // to test the property `skip`
        should("test skip") {
            // uncomment below to test the property
            //modelInstance.skip shouldBe ("TODO")
        }

    }
}
