/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.CreateCommitInput
import com.google.gerrit.client.model.FileChange

class CreateCommitInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateCommitInput
        //val modelInstance = CreateCommitInput()

        // to test the property `commitMessage`
        should("test commitMessage") {
            // uncomment below to test the property
            //modelInstance.commitMessage shouldBe ("TODO")
        }

        // to test the property `baseRevision`
        should("test baseRevision") {
            // uncomment below to test the property
            //modelInstance.baseRevision shouldBe ("TODO")
        }

        // to test the property `files`
        should("test files") {
            // uncomment below to test the property
            //modelInstance.files shouldBe ("TODO")
        }

        // to test the property `validationOptions`
        should("test validationOptions") {
            // uncomment below to test the property
            //modelInstance.validationOptions shouldBe ("TODO")
        }

    }
}
