/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.DashboardInfo
import com.google.gerrit.client.model.DashboardSectionInfo

class DashboardInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DashboardInfo
        //val modelInstance = DashboardInfo()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `project`
        should("test project") {
            // uncomment below to test the property
            //modelInstance.project shouldBe ("TODO")
        }

        // to test the property `definingProject`
        should("test definingProject") {
            // uncomment below to test the property
            //modelInstance.definingProject shouldBe ("TODO")
        }

        // to test the property `ref`
        should("test ref") {
            // uncomment below to test the property
            //modelInstance.ref shouldBe ("TODO")
        }

        // to test the property `path`
        should("test path") {
            // uncomment below to test the property
            //modelInstance.path shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `foreach`
        should("test foreach") {
            // uncomment below to test the property
            //modelInstance.foreach shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `isDefault`
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `sections`
        should("test sections") {
            // uncomment below to test the property
            //modelInstance.sections shouldBe ("TODO")
        }

    }
}
