/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.DeletedDraftCommentInfo
import com.google.gerrit.client.model.ChangeInfo
import com.google.gerrit.client.model.CommentInfo

class DeletedDraftCommentInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeletedDraftCommentInfo
        //val modelInstance = DeletedDraftCommentInfo()

        // to test the property `change`
        should("test change") {
            // uncomment below to test the property
            //modelInstance.change shouldBe ("TODO")
        }

        // to test the property `deleted`
        should("test deleted") {
            // uncomment below to test the property
            //modelInstance.deleted shouldBe ("TODO")
        }

    }
}
