/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.DeleteReviewerInput
import com.google.gerrit.client.model.NotifyHandling
import com.google.gerrit.client.model.NotifyInfo

class DeleteReviewerInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteReviewerInput
        //val modelInstance = DeleteReviewerInput()

        // to test the property `notify`
        should("test notify") {
            // uncomment below to test the property
            //modelInstance.notify shouldBe ("TODO")
        }

        // to test the property `notifyDetails`
        should("test notifyDetails") {
            // uncomment below to test the property
            //modelInstance.notifyDetails shouldBe ("TODO")
        }

    }
}
