/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.DiffPreferencesInfo
import com.google.gerrit.client.model.ResponsiveMode
import com.google.gerrit.client.model.Whitespace

class DiffPreferencesInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DiffPreferencesInfo
        //val modelInstance = DiffPreferencesInfo()

        // to test the property `context`
        should("test context") {
            // uncomment below to test the property
            //modelInstance.context shouldBe ("TODO")
        }

        // to test the property `tabSize`
        should("test tabSize") {
            // uncomment below to test the property
            //modelInstance.tabSize shouldBe ("TODO")
        }

        // to test the property `fontSize`
        should("test fontSize") {
            // uncomment below to test the property
            //modelInstance.fontSize shouldBe ("TODO")
        }

        // to test the property `lineLength`
        should("test lineLength") {
            // uncomment below to test the property
            //modelInstance.lineLength shouldBe ("TODO")
        }

        // to test the property `cursorBlinkRate`
        should("test cursorBlinkRate") {
            // uncomment below to test the property
            //modelInstance.cursorBlinkRate shouldBe ("TODO")
        }

        // to test the property `expandAllComments`
        should("test expandAllComments") {
            // uncomment below to test the property
            //modelInstance.expandAllComments shouldBe ("TODO")
        }

        // to test the property `intralineDifference`
        should("test intralineDifference") {
            // uncomment below to test the property
            //modelInstance.intralineDifference shouldBe ("TODO")
        }

        // to test the property `manualReview`
        should("test manualReview") {
            // uncomment below to test the property
            //modelInstance.manualReview shouldBe ("TODO")
        }

        // to test the property `showLineEndings`
        should("test showLineEndings") {
            // uncomment below to test the property
            //modelInstance.showLineEndings shouldBe ("TODO")
        }

        // to test the property `showTabs`
        should("test showTabs") {
            // uncomment below to test the property
            //modelInstance.showTabs shouldBe ("TODO")
        }

        // to test the property `showWhitespaceErrors`
        should("test showWhitespaceErrors") {
            // uncomment below to test the property
            //modelInstance.showWhitespaceErrors shouldBe ("TODO")
        }

        // to test the property `syntaxHighlighting`
        should("test syntaxHighlighting") {
            // uncomment below to test the property
            //modelInstance.syntaxHighlighting shouldBe ("TODO")
        }

        // to test the property `hideTopMenu`
        should("test hideTopMenu") {
            // uncomment below to test the property
            //modelInstance.hideTopMenu shouldBe ("TODO")
        }

        // to test the property `autoHideDiffTableHeader`
        should("test autoHideDiffTableHeader") {
            // uncomment below to test the property
            //modelInstance.autoHideDiffTableHeader shouldBe ("TODO")
        }

        // to test the property `hideLineNumbers`
        should("test hideLineNumbers") {
            // uncomment below to test the property
            //modelInstance.hideLineNumbers shouldBe ("TODO")
        }

        // to test the property `renderEntireFile`
        should("test renderEntireFile") {
            // uncomment below to test the property
            //modelInstance.renderEntireFile shouldBe ("TODO")
        }

        // to test the property `hideEmptyPane`
        should("test hideEmptyPane") {
            // uncomment below to test the property
            //modelInstance.hideEmptyPane shouldBe ("TODO")
        }

        // to test the property `matchBrackets`
        should("test matchBrackets") {
            // uncomment below to test the property
            //modelInstance.matchBrackets shouldBe ("TODO")
        }

        // to test the property `lineWrapping`
        should("test lineWrapping") {
            // uncomment below to test the property
            //modelInstance.lineWrapping shouldBe ("TODO")
        }

        // to test the property `responsiveMode`
        should("test responsiveMode") {
            // uncomment below to test the property
            //modelInstance.responsiveMode shouldBe ("TODO")
        }

        // to test the property `ignoreWhitespace`
        should("test ignoreWhitespace") {
            // uncomment below to test the property
            //modelInstance.ignoreWhitespace shouldBe ("TODO")
        }

        // to test the property `retainHeader`
        should("test retainHeader") {
            // uncomment below to test the property
            //modelInstance.retainHeader shouldBe ("TODO")
        }

        // to test the property `skipDeleted`
        should("test skipDeleted") {
            // uncomment below to test the property
            //modelInstance.skipDeleted shouldBe ("TODO")
        }

        // to test the property `skipUnchanged`
        should("test skipUnchanged") {
            // uncomment below to test the property
            //modelInstance.skipUnchanged shouldBe ("TODO")
        }

        // to test the property `skipUncommented`
        should("test skipUncommented") {
            // uncomment below to test the property
            //modelInstance.skipUncommented shouldBe ("TODO")
        }

    }
}
