/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.EmailInput

class EmailInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmailInput
        //val modelInstance = EmailInput()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `preferred`
        should("test preferred") {
            // uncomment below to test the property
            //modelInstance.preferred shouldBe ("TODO")
        }

        // to test the property `noConfirmation`
        should("test noConfirmation") {
            // uncomment below to test the property
            //modelInstance.noConfirmation shouldBe ("TODO")
        }

    }
}
