/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.FetchInfo

class FetchInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FetchInfo
        //val modelInstance = FetchInfo()

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `ref`
        should("test ref") {
            // uncomment below to test the property
            //modelInstance.ref shouldBe ("TODO")
        }

        // to test the property `commands`
        should("test commands") {
            // uncomment below to test the property
            //modelInstance.commands shouldBe ("TODO")
        }

    }
}
