/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.FileChange

class FileChangeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FileChange
        //val modelInstance = FileChange()

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `fileMode`
        should("test fileMode") {
            // uncomment below to test the property
            //modelInstance.fileMode shouldBe ("TODO")
        }

        // to test the property `delete`
        should("test delete") {
            // uncomment below to test the property
            //modelInstance.delete shouldBe ("TODO")
        }

        // to test the property `renameFrom`
        should("test renameFrom") {
            // uncomment below to test the property
            //modelInstance.renameFrom shouldBe ("TODO")
        }

    }
}
