/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.FixInput

class FixInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FixInput
        //val modelInstance = FixInput()

        // to test the property `deletePatchSetIfCommitMissing`
        should("test deletePatchSetIfCommitMissing") {
            // uncomment below to test the property
            //modelInstance.deletePatchSetIfCommitMissing shouldBe ("TODO")
        }

        // to test the property `expectMergedAs`
        should("test expectMergedAs") {
            // uncomment below to test the property
            //modelInstance.expectMergedAs shouldBe ("TODO")
        }

    }
}
