/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.GeneralPreferencesInfo
import com.google.gerrit.client.model.DateFormat
import com.google.gerrit.client.model.DefaultBase
import com.google.gerrit.client.model.DiffView
import com.google.gerrit.client.model.EmailFormat
import com.google.gerrit.client.model.EmailStrategy
import com.google.gerrit.client.model.MenuItem
import com.google.gerrit.client.model.Theme
import com.google.gerrit.client.model.TimeFormat

class GeneralPreferencesInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GeneralPreferencesInfo
        //val modelInstance = GeneralPreferencesInfo()

        // to test the property `changesPerPage`
        should("test changesPerPage") {
            // uncomment below to test the property
            //modelInstance.changesPerPage shouldBe ("TODO")
        }

        // to test the property `downloadScheme`
        should("test downloadScheme") {
            // uncomment below to test the property
            //modelInstance.downloadScheme shouldBe ("TODO")
        }

        // to test the property `theme`
        should("test theme") {
            // uncomment below to test the property
            //modelInstance.theme shouldBe ("TODO")
        }

        // to test the property `dateFormat`
        should("test dateFormat") {
            // uncomment below to test the property
            //modelInstance.dateFormat shouldBe ("TODO")
        }

        // to test the property `timeFormat`
        should("test timeFormat") {
            // uncomment below to test the property
            //modelInstance.timeFormat shouldBe ("TODO")
        }

        // to test the property `expandInlineDiffs`
        should("test expandInlineDiffs") {
            // uncomment below to test the property
            //modelInstance.expandInlineDiffs shouldBe ("TODO")
        }

        // to test the property `relativeDateInChangeTable`
        should("test relativeDateInChangeTable") {
            // uncomment below to test the property
            //modelInstance.relativeDateInChangeTable shouldBe ("TODO")
        }

        // to test the property `diffView`
        should("test diffView") {
            // uncomment below to test the property
            //modelInstance.diffView shouldBe ("TODO")
        }

        // to test the property `sizeBarInChangeTable`
        should("test sizeBarInChangeTable") {
            // uncomment below to test the property
            //modelInstance.sizeBarInChangeTable shouldBe ("TODO")
        }

        // to test the property `legacycidInChangeTable`
        should("test legacycidInChangeTable") {
            // uncomment below to test the property
            //modelInstance.legacycidInChangeTable shouldBe ("TODO")
        }

        // to test the property `muteCommonPathPrefixes`
        should("test muteCommonPathPrefixes") {
            // uncomment below to test the property
            //modelInstance.muteCommonPathPrefixes shouldBe ("TODO")
        }

        // to test the property `signedOffBy`
        should("test signedOffBy") {
            // uncomment below to test the property
            //modelInstance.signedOffBy shouldBe ("TODO")
        }

        // to test the property `emailStrategy`
        should("test emailStrategy") {
            // uncomment below to test the property
            //modelInstance.emailStrategy shouldBe ("TODO")
        }

        // to test the property `emailFormat`
        should("test emailFormat") {
            // uncomment below to test the property
            //modelInstance.emailFormat shouldBe ("TODO")
        }

        // to test the property `defaultBaseForMerges`
        should("test defaultBaseForMerges") {
            // uncomment below to test the property
            //modelInstance.defaultBaseForMerges shouldBe ("TODO")
        }

        // to test the property `publishCommentsOnPush`
        should("test publishCommentsOnPush") {
            // uncomment below to test the property
            //modelInstance.publishCommentsOnPush shouldBe ("TODO")
        }

        // to test the property `disableKeyboardShortcuts`
        should("test disableKeyboardShortcuts") {
            // uncomment below to test the property
            //modelInstance.disableKeyboardShortcuts shouldBe ("TODO")
        }

        // to test the property `disableTokenHighlighting`
        should("test disableTokenHighlighting") {
            // uncomment below to test the property
            //modelInstance.disableTokenHighlighting shouldBe ("TODO")
        }

        // to test the property `workInProgressByDefault`
        should("test workInProgressByDefault") {
            // uncomment below to test the property
            //modelInstance.workInProgressByDefault shouldBe ("TODO")
        }

        // to test the property `my`
        should("test my") {
            // uncomment below to test the property
            //modelInstance.my shouldBe ("TODO")
        }

        // to test the property `changeTable`
        should("test changeTable") {
            // uncomment below to test the property
            //modelInstance.changeTable shouldBe ("TODO")
        }

        // to test the property `allowBrowserNotifications`
        should("test allowBrowserNotifications") {
            // uncomment below to test the property
            //modelInstance.allowBrowserNotifications shouldBe ("TODO")
        }

        // to test the property `allowSuggestCodeWhileCommenting`
        should("test allowSuggestCodeWhileCommenting") {
            // uncomment below to test the property
            //modelInstance.allowSuggestCodeWhileCommenting shouldBe ("TODO")
        }

        // to test the property `allowAutocompletingComments`
        should("test allowAutocompletingComments") {
            // uncomment below to test the property
            //modelInstance.allowAutocompletingComments shouldBe ("TODO")
        }

        // to test the property `aiChatSelectedModel`
        should("test aiChatSelectedModel") {
            // uncomment below to test the property
            //modelInstance.aiChatSelectedModel shouldBe ("TODO")
        }

        // to test the property `labelFilter`
        should("test labelFilter") {
            // uncomment below to test the property
            //modelInstance.labelFilter shouldBe ("TODO")
        }

        // to test the property `diffPageSidebar`
        should("test diffPageSidebar") {
            // uncomment below to test the property
            //modelInstance.diffPageSidebar shouldBe ("TODO")
        }

    }
}
