/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.GerritInfo

class GerritInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GerritInfo
        //val modelInstance = GerritInfo()

        // to test the property `allProjects`
        should("test allProjects") {
            // uncomment below to test the property
            //modelInstance.allProjects shouldBe ("TODO")
        }

        // to test the property `allUsers`
        should("test allUsers") {
            // uncomment below to test the property
            //modelInstance.allUsers shouldBe ("TODO")
        }

        // to test the property `docSearch`
        should("test docSearch") {
            // uncomment below to test the property
            //modelInstance.docSearch shouldBe ("TODO")
        }

        // to test the property `docUrl`
        should("test docUrl") {
            // uncomment below to test the property
            //modelInstance.docUrl shouldBe ("TODO")
        }

        // to test the property `editGpgKeys`
        should("test editGpgKeys") {
            // uncomment below to test the property
            //modelInstance.editGpgKeys shouldBe ("TODO")
        }

        // to test the property `reportBugUrl`
        should("test reportBugUrl") {
            // uncomment below to test the property
            //modelInstance.reportBugUrl shouldBe ("TODO")
        }

        // to test the property `primaryWeblinkName`
        should("test primaryWeblinkName") {
            // uncomment below to test the property
            //modelInstance.primaryWeblinkName shouldBe ("TODO")
        }

        // to test the property `instanceId`
        should("test instanceId") {
            // uncomment below to test the property
            //modelInstance.instanceId shouldBe ("TODO")
        }

        // to test the property `defaultBranch`
        should("test defaultBranch") {
            // uncomment below to test the property
            //modelInstance.defaultBranch shouldBe ("TODO")
        }

        // to test the property `projectStatePredicateEnabled`
        should("test projectStatePredicateEnabled") {
            // uncomment below to test the property
            //modelInstance.projectStatePredicateEnabled shouldBe ("TODO")
        }

    }
}
