/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.GroupOptionsInfo

class GroupOptionsInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GroupOptionsInfo
        //val modelInstance = GroupOptionsInfo()

        // to test the property `visibleToAll`
        should("test visibleToAll") {
            // uncomment below to test the property
            //modelInstance.visibleToAll shouldBe ("TODO")
        }

    }
}
