/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.IndexProjectInput

class IndexProjectInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IndexProjectInput
        //val modelInstance = IndexProjectInput()

        // to test the property `indexChildren`
        should("test indexChildren") {
            // uncomment below to test the property
            //modelInstance.indexChildren shouldBe ("TODO")
        }

        // to test the property `async`
        should("test async") {
            // uncomment below to test the property
            //modelInstance.async shouldBe ("TODO")
        }

    }
}
