/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.JvmSummaryInfo

class JvmSummaryInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JvmSummaryInfo
        //val modelInstance = JvmSummaryInfo()

        // to test the property `vmVendor`
        should("test vmVendor") {
            // uncomment below to test the property
            //modelInstance.vmVendor shouldBe ("TODO")
        }

        // to test the property `vmName`
        should("test vmName") {
            // uncomment below to test the property
            //modelInstance.vmName shouldBe ("TODO")
        }

        // to test the property `vmVersion`
        should("test vmVersion") {
            // uncomment below to test the property
            //modelInstance.vmVersion shouldBe ("TODO")
        }

        // to test the property `osName`
        should("test osName") {
            // uncomment below to test the property
            //modelInstance.osName shouldBe ("TODO")
        }

        // to test the property `osVersion`
        should("test osVersion") {
            // uncomment below to test the property
            //modelInstance.osVersion shouldBe ("TODO")
        }

        // to test the property `osArch`
        should("test osArch") {
            // uncomment below to test the property
            //modelInstance.osArch shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `host`
        should("test host") {
            // uncomment below to test the property
            //modelInstance.host shouldBe ("TODO")
        }

        // to test the property `currentWorkingDirectory`
        should("test currentWorkingDirectory") {
            // uncomment below to test the property
            //modelInstance.currentWorkingDirectory shouldBe ("TODO")
        }

        // to test the property `site`
        should("test site") {
            // uncomment below to test the property
            //modelInstance.site shouldBe ("TODO")
        }

    }
}
