/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.Label
import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.LabelStatus

class LabelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Label
        //val modelInstance = Label()

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `appliedBy`
        should("test appliedBy") {
            // uncomment below to test the property
            //modelInstance.appliedBy shouldBe ("TODO")
        }

    }
}
