/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.LabelTypeInfo

class LabelTypeInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LabelTypeInfo
        //val modelInstance = LabelTypeInfo()

        // to test the property `propertyValues`
        should("test propertyValues") {
            // uncomment below to test the property
            //modelInstance.propertyValues shouldBe ("TODO")
        }

        // to test the property `defaultValue`
        should("test defaultValue") {
            // uncomment below to test the property
            //modelInstance.defaultValue shouldBe ("TODO")
        }

    }
}
