/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.MergeInput

class MergeInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MergeInput
        //val modelInstance = MergeInput()

        // to test the property `source`
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `sourceBranch`
        should("test sourceBranch") {
            // uncomment below to test the property
            //modelInstance.sourceBranch shouldBe ("TODO")
        }

        // to test the property `strategy`
        should("test strategy") {
            // uncomment below to test the property
            //modelInstance.strategy shouldBe ("TODO")
        }

        // to test the property `allowConflicts`
        should("test allowConflicts") {
            // uncomment below to test the property
            //modelInstance.allowConflicts shouldBe ("TODO")
        }

    }
}
