/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.MergePatchSetInput
import com.google.gerrit.client.model.AccountInput
import com.google.gerrit.client.model.MergeInput

class MergePatchSetInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MergePatchSetInput
        //val modelInstance = MergePatchSetInput()

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `inheritParent`
        should("test inheritParent") {
            // uncomment below to test the property
            //modelInstance.inheritParent shouldBe ("TODO")
        }

        // to test the property `baseChange`
        should("test baseChange") {
            // uncomment below to test the property
            //modelInstance.baseChange shouldBe ("TODO")
        }

        // to test the property `merge`
        should("test merge") {
            // uncomment below to test the property
            //modelInstance.merge shouldBe ("TODO")
        }

        // to test the property `author`
        should("test author") {
            // uncomment below to test the property
            //modelInstance.author shouldBe ("TODO")
        }

        // to test the property `validationOptions`
        should("test validationOptions") {
            // uncomment below to test the property
            //modelInstance.validationOptions shouldBe ("TODO")
        }

    }
}
