/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.MoveInput

class MoveInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MoveInput
        //val modelInstance = MoveInput()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `destinationBranch`
        should("test destinationBranch") {
            // uncomment below to test the property
            //modelInstance.destinationBranch shouldBe ("TODO")
        }

        // to test the property `keepAllVotes`
        should("test keepAllVotes") {
            // uncomment below to test the property
            //modelInstance.keepAllVotes shouldBe ("TODO")
        }

    }
}
