/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ParentInfo

class ParentInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ParentInfo
        //val modelInstance = ParentInfo()

        // to test the property `branchName`
        should("test branchName") {
            // uncomment below to test the property
            //modelInstance.branchName shouldBe ("TODO")
        }

        // to test the property `commitId`
        should("test commitId") {
            // uncomment below to test the property
            //modelInstance.commitId shouldBe ("TODO")
        }

        // to test the property `isMergedInTargetBranch`
        should("test isMergedInTargetBranch") {
            // uncomment below to test the property
            //modelInstance.isMergedInTargetBranch shouldBe ("TODO")
        }

        // to test the property `changeId`
        should("test changeId") {
            // uncomment below to test the property
            //modelInstance.changeId shouldBe ("TODO")
        }

        // to test the property `changeNumber`
        should("test changeNumber") {
            // uncomment below to test the property
            //modelInstance.changeNumber shouldBe ("TODO")
        }

        // to test the property `patchSetNumber`
        should("test patchSetNumber") {
            // uncomment below to test the property
            //modelInstance.patchSetNumber shouldBe ("TODO")
        }

        // to test the property `changeStatus`
        should("test changeStatus") {
            // uncomment below to test the property
            //modelInstance.changeStatus shouldBe ("TODO")
        }

    }
}
