/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.PluginInfo

class PluginInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PluginInfo
        //val modelInstance = PluginInfo()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `apiVersion`
        should("test apiVersion") {
            // uncomment below to test the property
            //modelInstance.apiVersion shouldBe ("TODO")
        }

        // to test the property `indexUrl`
        should("test indexUrl") {
            // uncomment below to test the property
            //modelInstance.indexUrl shouldBe ("TODO")
        }

        // to test the property `filename`
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

        // to test the property `disabled`
        should("test disabled") {
            // uncomment below to test the property
            //modelInstance.disabled shouldBe ("TODO")
        }

    }
}
