/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ProjectWatchInfo

class ProjectWatchInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectWatchInfo
        //val modelInstance = ProjectWatchInfo()

        // to test the property `project`
        should("test project") {
            // uncomment below to test the property
            //modelInstance.project shouldBe ("TODO")
        }

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

        // to test the property `problem`
        should("test problem") {
            // uncomment below to test the property
            //modelInstance.problem shouldBe ("TODO")
        }

        // to test the property `notifyNewChanges`
        should("test notifyNewChanges") {
            // uncomment below to test the property
            //modelInstance.notifyNewChanges shouldBe ("TODO")
        }

        // to test the property `notifyNewPatchSets`
        should("test notifyNewPatchSets") {
            // uncomment below to test the property
            //modelInstance.notifyNewPatchSets shouldBe ("TODO")
        }

        // to test the property `notifyAllComments`
        should("test notifyAllComments") {
            // uncomment below to test the property
            //modelInstance.notifyAllComments shouldBe ("TODO")
        }

        // to test the property `notifySubmittedChanges`
        should("test notifySubmittedChanges") {
            // uncomment below to test the property
            //modelInstance.notifySubmittedChanges shouldBe ("TODO")
        }

        // to test the property `notifyAbandonedChanges`
        should("test notifyAbandonedChanges") {
            // uncomment below to test the property
            //modelInstance.notifyAbandonedChanges shouldBe ("TODO")
        }

    }
}
