/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.RebaseInput

class RebaseInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RebaseInput
        //val modelInstance = RebaseInput()

        // to test the property `base`
        should("test base") {
            // uncomment below to test the property
            //modelInstance.base shouldBe ("TODO")
        }

        // to test the property `strategy`
        should("test strategy") {
            // uncomment below to test the property
            //modelInstance.strategy shouldBe ("TODO")
        }

        // to test the property `allowConflicts`
        should("test allowConflicts") {
            // uncomment below to test the property
            //modelInstance.allowConflicts shouldBe ("TODO")
        }

        // to test the property `onBehalfOfUploader`
        should("test onBehalfOfUploader") {
            // uncomment below to test the property
            //modelInstance.onBehalfOfUploader shouldBe ("TODO")
        }

        // to test the property `validationOptions`
        should("test validationOptions") {
            // uncomment below to test the property
            //modelInstance.validationOptions shouldBe ("TODO")
        }

        // to test the property `committerEmail`
        should("test committerEmail") {
            // uncomment below to test the property
            //modelInstance.committerEmail shouldBe ("TODO")
        }

    }
}
