/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.RevertInput
import com.google.gerrit.client.model.NotifyHandling
import com.google.gerrit.client.model.NotifyInfo

class RevertInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RevertInput
        //val modelInstance = RevertInput()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `notify`
        should("test notify") {
            // uncomment below to test the property
            //modelInstance.notify shouldBe ("TODO")
        }

        // to test the property `notifyDetails`
        should("test notifyDetails") {
            // uncomment below to test the property
            //modelInstance.notifyDetails shouldBe ("TODO")
        }

        // to test the property `topic`
        should("test topic") {
            // uncomment below to test the property
            //modelInstance.topic shouldBe ("TODO")
        }

        // to test the property `workInProgress`
        should("test workInProgress") {
            // uncomment below to test the property
            //modelInstance.workInProgress shouldBe ("TODO")
        }

        // to test the property `validationOptions`
        should("test validationOptions") {
            // uncomment below to test the property
            //modelInstance.validationOptions shouldBe ("TODO")
        }

    }
}
