/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ReviewResult
import com.google.gerrit.client.model.ChangeInfo
import com.google.gerrit.client.model.ReviewerResult

class ReviewResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReviewResult
        //val modelInstance = ReviewResult()

        // to test the property `labels`
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `reviewers`
        should("test reviewers") {
            // uncomment below to test the property
            //modelInstance.reviewers shouldBe ("TODO")
        }

        // to test the property `ready`
        should("test ready") {
            // uncomment below to test the property
            //modelInstance.ready shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `changeInfo`
        should("test changeInfo") {
            // uncomment below to test the property
            //modelInstance.changeInfo shouldBe ("TODO")
        }

    }
}
