/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.ReviewerInput
import com.google.gerrit.client.model.NotifyHandling
import com.google.gerrit.client.model.NotifyInfo
import com.google.gerrit.client.model.ReviewerState

class ReviewerInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReviewerInput
        //val modelInstance = ReviewerInput()

        // to test the property `reviewer`
        should("test reviewer") {
            // uncomment below to test the property
            //modelInstance.reviewer shouldBe ("TODO")
        }

        // to test the property `confirmed`
        should("test confirmed") {
            // uncomment below to test the property
            //modelInstance.confirmed shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `notify`
        should("test notify") {
            // uncomment below to test the property
            //modelInstance.notify shouldBe ("TODO")
        }

        // to test the property `notifyDetails`
        should("test notifyDetails") {
            // uncomment below to test the property
            //modelInstance.notifyDetails shouldBe ("TODO")
        }

        // to test the property `onBehalfOf`
        should("test onBehalfOf") {
            // uncomment below to test the property
            //modelInstance.onBehalfOf shouldBe ("TODO")
        }

    }
}
