/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.SubmitRequirementResultInfo
import com.google.gerrit.client.model.SubmitRequirementExpressionInfo
import com.google.gerrit.client.model.SubmitRequirementResultInfoStatus

class SubmitRequirementResultInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubmitRequirementResultInfo
        //val modelInstance = SubmitRequirementResultInfo()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `isLegacy`
        should("test isLegacy") {
            // uncomment below to test the property
            //modelInstance.isLegacy shouldBe ("TODO")
        }

        // to test the property `applicabilityExpressionResult`
        should("test applicabilityExpressionResult") {
            // uncomment below to test the property
            //modelInstance.applicabilityExpressionResult shouldBe ("TODO")
        }

        // to test the property `submittabilityExpressionResult`
        should("test submittabilityExpressionResult") {
            // uncomment below to test the property
            //modelInstance.submittabilityExpressionResult shouldBe ("TODO")
        }

        // to test the property `overrideExpressionResult`
        should("test overrideExpressionResult") {
            // uncomment below to test the property
            //modelInstance.overrideExpressionResult shouldBe ("TODO")
        }

    }
}
