/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.SubmitRequirementInfo

class SubmitRequirementInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubmitRequirementInfo
        //val modelInstance = SubmitRequirementInfo()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `projectName`
        should("test projectName") {
            // uncomment below to test the property
            //modelInstance.projectName shouldBe ("TODO")
        }

        // to test the property `applicabilityExpression`
        should("test applicabilityExpression") {
            // uncomment below to test the property
            //modelInstance.applicabilityExpression shouldBe ("TODO")
        }

        // to test the property `submittabilityExpression`
        should("test submittabilityExpression") {
            // uncomment below to test the property
            //modelInstance.submittabilityExpression shouldBe ("TODO")
        }

        // to test the property `overrideExpression`
        should("test overrideExpression") {
            // uncomment below to test the property
            //modelInstance.overrideExpression shouldBe ("TODO")
        }

        // to test the property `allowOverrideInChildProjects`
        should("test allowOverrideInChildProjects") {
            // uncomment below to test the property
            //modelInstance.allowOverrideInChildProjects shouldBe ("TODO")
        }

    }
}
