/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.model.TestSubmitRuleInfo
import com.google.gerrit.client.model.AccountInfo

class TestSubmitRuleInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestSubmitRuleInfo
        //val modelInstance = TestSubmitRuleInfo()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `errorMessage`
        should("test errorMessage") {
            // uncomment below to test the property
            //modelInstance.errorMessage shouldBe ("TODO")
        }

        // to test the property `ok`
        should("test ok") {
            // uncomment below to test the property
            //modelInstance.ok shouldBe ("TODO")
        }

        // to test the property `reject`
        should("test reject") {
            // uncomment below to test the property
            //modelInstance.reject shouldBe ("TODO")
        }

        // to test the property `need`
        should("test need") {
            // uncomment below to test the property
            //modelInstance.need shouldBe ("TODO")
        }

        // to test the property `may`
        should("test may") {
            // uncomment below to test the property
            //modelInstance.may shouldBe ("TODO")
        }

        // to test the property `impossible`
        should("test impossible") {
            // uncomment below to test the property
            //modelInstance.impossible shouldBe ("TODO")
        }

    }
}
