/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.api.AccessApi
import com.google.gerrit.client.model.ProjectAccessInfo

class AccessApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccessApi
        //val apiInstance = AccessApi()

        // to test getAccess
        should("test getAccess") {
            // uncomment below to test getAccess
            //val project : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val result : kotlin.collections.Map<kotlin.String, ProjectAccessInfo> = apiInstance.getAccess(project)
            //result shouldBe ("TODO")
        }

    }
}
