/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.api.AccountsApi
import com.google.gerrit.client.model.AccountDetailInfo
import com.google.gerrit.client.model.AccountExternalIdInfo
import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.AccountInput
import com.google.gerrit.client.model.AccountStateInfo
import com.google.gerrit.client.model.AgreementInfo
import com.google.gerrit.client.model.AgreementInput
import com.google.gerrit.client.model.AuthTokenInfo
import com.google.gerrit.client.model.AuthTokenInput
import com.google.gerrit.client.model.DeleteDraftCommentsInput
import com.google.gerrit.client.model.DeletedDraftCommentInfo
import com.google.gerrit.client.model.DiffPreferencesInfo
import com.google.gerrit.client.model.DisplayNameInput
import com.google.gerrit.client.model.EditPreferencesInfo
import com.google.gerrit.client.model.EmailInfo
import com.google.gerrit.client.model.EmailInput
import com.google.gerrit.client.model.GeneralPreferencesInfo
import com.google.gerrit.client.model.GroupInfo
import com.google.gerrit.client.model.HttpPasswordInput
import com.google.gerrit.client.model.NameInput
import com.google.gerrit.client.model.ProjectWatchInfo
import com.google.gerrit.client.model.SshKeyInfo
import com.google.gerrit.client.model.StatusInput
import com.google.gerrit.client.model.UsernameInput

class AccountsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountsApi
        //val apiInstance = AccountsApi()

        // to test deleteAccountsAccountId
        should("test deleteAccountsAccountId") {
            // uncomment below to test deleteAccountsAccountId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //apiInstance.deleteAccountsAccountId(accountId)
        }

        // to test deleteAccountsAccountIdActive
        should("test deleteAccountsAccountIdActive") {
            // uncomment below to test deleteAccountsAccountIdActive
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.deleteAccountsAccountIdActive(accountId)
            //result shouldBe ("TODO")
        }

        // to test deleteAccountsAccountIdEmailsEmailId
        should("test deleteAccountsAccountIdEmailsEmailId") {
            // uncomment below to test deleteAccountsAccountIdEmailsEmailId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val emailId : kotlin.String = emailId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.deleteAccountsAccountIdEmailsEmailId(accountId, emailId)
            //result shouldBe ("TODO")
        }

        // to test deleteAccountsAccountIdName
        should("test deleteAccountsAccountIdName") {
            // uncomment below to test deleteAccountsAccountIdName
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.deleteAccountsAccountIdName(accountId)
            //result shouldBe ("TODO")
        }

        // to test deleteAccountsAccountIdPasswordHttp
        should("test deleteAccountsAccountIdPasswordHttp") {
            // uncomment below to test deleteAccountsAccountIdPasswordHttp
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.deleteAccountsAccountIdPasswordHttp(accountId)
            //result shouldBe ("TODO")
        }

        // to test deleteAccountsAccountIdSshkeysSshKeyId
        should("test deleteAccountsAccountIdSshkeysSshKeyId") {
            // uncomment below to test deleteAccountsAccountIdSshkeysSshKeyId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val sshKeyId : kotlin.String = sshKeyId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.deleteAccountsAccountIdSshkeysSshKeyId(accountId, sshKeyId)
            //result shouldBe ("TODO")
        }

        // to test deleteAccountsAccountIdStarredChangesStarredChangeId
        should("test deleteAccountsAccountIdStarredChangesStarredChangeId") {
            // uncomment below to test deleteAccountsAccountIdStarredChangesStarredChangeId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val starredChangeId : kotlin.String = starredChangeId_example // kotlin.String | 
            //apiInstance.deleteAccountsAccountIdStarredChangesStarredChangeId(accountId, starredChangeId)
        }

        // to test deleteAccountsAccountIdTokensTokenId
        should("test deleteAccountsAccountIdTokensTokenId") {
            // uncomment below to test deleteAccountsAccountIdTokensTokenId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val tokenId : kotlin.String = tokenId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.deleteAccountsAccountIdTokensTokenId(accountId, tokenId)
            //result shouldBe ("TODO")
        }

        // to test getAccounts
        should("test getAccounts") {
            // uncomment below to test getAccounts
            //val O : kotlin.String = O_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val o : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val query : kotlin.String = query_example // kotlin.String | 
            //val start : kotlin.Int = 56 // kotlin.Int | 
            //val suggest : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.collections.List<AccountInfo> = apiInstance.getAccounts(O, limit, o, query, start, suggest)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountId
        should("test getAccountsAccountId") {
            // uncomment below to test getAccountsAccountId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : AccountInfo = apiInstance.getAccountsAccountId(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdActive
        should("test getAccountsAccountIdActive") {
            // uncomment below to test getAccountsAccountIdActive
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.getAccountsAccountIdActive(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdAgreements
        should("test getAccountsAccountIdAgreements") {
            // uncomment below to test getAccountsAccountIdAgreements
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.collections.List<AgreementInfo> = apiInstance.getAccountsAccountIdAgreements(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdAvatar
        should("test getAccountsAccountIdAvatar") {
            // uncomment below to test getAccountsAccountIdAvatar
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val size : kotlin.Int = 56 // kotlin.Int | 
            //apiInstance.getAccountsAccountIdAvatar(accountId, size)
        }

        // to test getAccountsAccountIdAvatarChangeUrl
        should("test getAccountsAccountIdAvatarChangeUrl") {
            // uncomment below to test getAccountsAccountIdAvatarChangeUrl
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.getAccountsAccountIdAvatarChangeUrl(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdCapabilities
        should("test getAccountsAccountIdCapabilities") {
            // uncomment below to test getAccountsAccountIdCapabilities
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val q : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getAccountsAccountIdCapabilities(accountId, q)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdCapabilitiesCapabilityId
        should("test getAccountsAccountIdCapabilitiesCapabilityId") {
            // uncomment below to test getAccountsAccountIdCapabilitiesCapabilityId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val capabilityId : kotlin.String = capabilityId_example // kotlin.String | 
            //val result : java.io.File = apiInstance.getAccountsAccountIdCapabilitiesCapabilityId(accountId, capabilityId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdDetail
        should("test getAccountsAccountIdDetail") {
            // uncomment below to test getAccountsAccountIdDetail
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : AccountDetailInfo = apiInstance.getAccountsAccountIdDetail(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdEmails
        should("test getAccountsAccountIdEmails") {
            // uncomment below to test getAccountsAccountIdEmails
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.collections.List<EmailInfo> = apiInstance.getAccountsAccountIdEmails(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdEmailsEmailId
        should("test getAccountsAccountIdEmailsEmailId") {
            // uncomment below to test getAccountsAccountIdEmailsEmailId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val emailId : kotlin.String = emailId_example // kotlin.String | 
            //val result : EmailInfo = apiInstance.getAccountsAccountIdEmailsEmailId(accountId, emailId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdExternalIds
        should("test getAccountsAccountIdExternalIds") {
            // uncomment below to test getAccountsAccountIdExternalIds
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.collections.List<AccountExternalIdInfo> = apiInstance.getAccountsAccountIdExternalIds(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdGroups
        should("test getAccountsAccountIdGroups") {
            // uncomment below to test getAccountsAccountIdGroups
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.collections.List<GroupInfo> = apiInstance.getAccountsAccountIdGroups(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdName
        should("test getAccountsAccountIdName") {
            // uncomment below to test getAccountsAccountIdName
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.getAccountsAccountIdName(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdPreferences
        should("test getAccountsAccountIdPreferences") {
            // uncomment below to test getAccountsAccountIdPreferences
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : GeneralPreferencesInfo = apiInstance.getAccountsAccountIdPreferences(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdPreferencesDiff
        should("test getAccountsAccountIdPreferencesDiff") {
            // uncomment below to test getAccountsAccountIdPreferencesDiff
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : DiffPreferencesInfo = apiInstance.getAccountsAccountIdPreferencesDiff(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdPreferencesEdit
        should("test getAccountsAccountIdPreferencesEdit") {
            // uncomment below to test getAccountsAccountIdPreferencesEdit
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : EditPreferencesInfo = apiInstance.getAccountsAccountIdPreferencesEdit(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdSshkeys
        should("test getAccountsAccountIdSshkeys") {
            // uncomment below to test getAccountsAccountIdSshkeys
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.collections.List<SshKeyInfo> = apiInstance.getAccountsAccountIdSshkeys(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdSshkeysSshKeyId
        should("test getAccountsAccountIdSshkeysSshKeyId") {
            // uncomment below to test getAccountsAccountIdSshkeysSshKeyId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val sshKeyId : kotlin.String = sshKeyId_example // kotlin.String | 
            //val result : SshKeyInfo = apiInstance.getAccountsAccountIdSshkeysSshKeyId(accountId, sshKeyId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdStarredChanges
        should("test getAccountsAccountIdStarredChanges") {
            // uncomment below to test getAccountsAccountIdStarredChanges
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.getAccountsAccountIdStarredChanges(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdState
        should("test getAccountsAccountIdState") {
            // uncomment below to test getAccountsAccountIdState
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : AccountStateInfo = apiInstance.getAccountsAccountIdState(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdStatus
        should("test getAccountsAccountIdStatus") {
            // uncomment below to test getAccountsAccountIdStatus
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.getAccountsAccountIdStatus(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdTokens
        should("test getAccountsAccountIdTokens") {
            // uncomment below to test getAccountsAccountIdTokens
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.collections.List<AuthTokenInfo> = apiInstance.getAccountsAccountIdTokens(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdUsername
        should("test getAccountsAccountIdUsername") {
            // uncomment below to test getAccountsAccountIdUsername
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.getAccountsAccountIdUsername(accountId)
            //result shouldBe ("TODO")
        }

        // to test getAccountsAccountIdWatchedProjects
        should("test getAccountsAccountIdWatchedProjects") {
            // uncomment below to test getAccountsAccountIdWatchedProjects
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.collections.List<ProjectWatchInfo> = apiInstance.getAccountsAccountIdWatchedProjects(accountId)
            //result shouldBe ("TODO")
        }

        // to test postAccountsAccountIdDraftsDelete
        should("test postAccountsAccountIdDraftsDelete") {
            // uncomment below to test postAccountsAccountIdDraftsDelete
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val deleteDraftCommentsInput : DeleteDraftCommentsInput = {"query":"is:abandoned"} // DeleteDraftCommentsInput | 
            //val result : kotlin.collections.List<DeletedDraftCommentInfo> = apiInstance.postAccountsAccountIdDraftsDelete(accountId, deleteDraftCommentsInput)
            //result shouldBe ("TODO")
        }

        // to test postAccountsAccountIdExternalIdsDelete
        should("test postAccountsAccountIdExternalIdsDelete") {
            // uncomment below to test postAccountsAccountIdExternalIdsDelete
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val requestBody : kotlin.collections.List<kotlin.String> = ["mailto:john.doe@example.com"] // kotlin.collections.List<kotlin.String> | 
            //apiInstance.postAccountsAccountIdExternalIdsDelete(accountId, requestBody)
        }

        // to test postAccountsAccountIdIndex
        should("test postAccountsAccountIdIndex") {
            // uncomment below to test postAccountsAccountIdIndex
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //apiInstance.postAccountsAccountIdIndex(accountId)
        }

        // to test postAccountsAccountIdSshkeys
        should("test postAccountsAccountIdSshkeys") {
            // uncomment below to test postAccountsAccountIdSshkeys
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val body : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val result : SshKeyInfo = apiInstance.postAccountsAccountIdSshkeys(accountId, body)
            //result shouldBe ("TODO")
        }

        // to test postAccountsAccountIdWatchedProjects
        should("test postAccountsAccountIdWatchedProjects") {
            // uncomment below to test postAccountsAccountIdWatchedProjects
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val projectWatchInfo : kotlin.collections.List<ProjectWatchInfo> =  // kotlin.collections.List<ProjectWatchInfo> | 
            //val result : kotlin.collections.List<ProjectWatchInfo> = apiInstance.postAccountsAccountIdWatchedProjects(accountId, projectWatchInfo)
            //result shouldBe ("TODO")
        }

        // to test postAccountsAccountIdWatchedProjectsDelete
        should("test postAccountsAccountIdWatchedProjectsDelete") {
            // uncomment below to test postAccountsAccountIdWatchedProjectsDelete
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val projectWatchInfo : kotlin.collections.List<ProjectWatchInfo> = [{"project":"Test Project 1","filter":"branch:master"}] // kotlin.collections.List<ProjectWatchInfo> | 
            //apiInstance.postAccountsAccountIdWatchedProjectsDelete(accountId, projectWatchInfo)
        }

        // to test putAccountsAccountId
        should("test putAccountsAccountId") {
            // uncomment below to test putAccountsAccountId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val accountInput : AccountInput = {"name":"John Doe","display_name":"Super John","email":"john.doe@example.com","ssh_key":"ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0T...YImydZAw==","tokens":[{"id":"token1","token":"19D9aIn7zePb"}],"groups":["MyProject-Owners"]} // AccountInput | 
            //val result : AccountInfo = apiInstance.putAccountsAccountId(accountId, accountInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdActive
        should("test putAccountsAccountIdActive") {
            // uncomment below to test putAccountsAccountIdActive
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdActive(accountId)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdAgreements
        should("test putAccountsAccountIdAgreements") {
            // uncomment below to test putAccountsAccountIdAgreements
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val agreementInput : AgreementInput = {"name":"Individual"} // AgreementInput | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdAgreements(accountId, agreementInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdDisplayname
        should("test putAccountsAccountIdDisplayname") {
            // uncomment below to test putAccountsAccountIdDisplayname
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val displayNameInput : DisplayNameInput = {"display_name":"John"} // DisplayNameInput | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdDisplayname(accountId, displayNameInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdEmailsEmailId
        should("test putAccountsAccountIdEmailsEmailId") {
            // uncomment below to test putAccountsAccountIdEmailsEmailId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val emailId : kotlin.String = emailId_example // kotlin.String | 
            //val emailInput : EmailInput = {} // EmailInput | 
            //val result : EmailInfo = apiInstance.putAccountsAccountIdEmailsEmailId(accountId, emailId, emailInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdEmailsEmailIdAvatar
        should("test putAccountsAccountIdEmailsEmailIdAvatar") {
            // uncomment below to test putAccountsAccountIdEmailsEmailIdAvatar
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val emailId : kotlin.String = emailId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdEmailsEmailIdAvatar(accountId, emailId)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdEmailsEmailIdPreferred
        should("test putAccountsAccountIdEmailsEmailIdPreferred") {
            // uncomment below to test putAccountsAccountIdEmailsEmailIdPreferred
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val emailId : kotlin.String = emailId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdEmailsEmailIdPreferred(accountId, emailId)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdName
        should("test putAccountsAccountIdName") {
            // uncomment below to test putAccountsAccountIdName
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val nameInput : NameInput = {"name":"John F. Doe"} // NameInput | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdName(accountId, nameInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdPasswordHttp
        should("test putAccountsAccountIdPasswordHttp") {
            // uncomment below to test putAccountsAccountIdPasswordHttp
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val httpPasswordInput : HttpPasswordInput = {"generate":true} // HttpPasswordInput | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdPasswordHttp(accountId, httpPasswordInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdPreferences
        should("test putAccountsAccountIdPreferences") {
            // uncomment below to test putAccountsAccountIdPreferences
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val generalPreferencesInfo : GeneralPreferencesInfo = {"changes_per_page":50,"theme":"DARK","expand_inline_diffs":true,"date_format":"STD","time_format":"HHMM_12","size_bar_in_change_table":true,"disable_keyboard_shortcuts":true,"disable_token_highlighting":true,"allow_browser_notifications":false,"allow_suggest_code_while_commenting":false,"allow_autocompleting_comments":false,"ai_chat_selected_model":"test-ai-model","diff_page_sidebar":"NONE","diff_view":"SIDE_BY_SIDE","mute_common_path_prefixes":true,"my":[{"url":"#/dashboard/self","name":"Changes"},{"url":"#/q/has:draft","name":"Draft Comments"},{"url":"#/q/is:watched+is:open","name":"Watched Changes"},{"url":"#/q/is:starred","name":"Starred Changes"},{"url":"#/groups/self","name":"Groups"}],"change_table":["Subject","Owner"]} // GeneralPreferencesInfo | 
            //val result : GeneralPreferencesInfo = apiInstance.putAccountsAccountIdPreferences(accountId, generalPreferencesInfo)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdPreferencesDiff
        should("test putAccountsAccountIdPreferencesDiff") {
            // uncomment below to test putAccountsAccountIdPreferencesDiff
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val diffPreferencesInfo : DiffPreferencesInfo = {"context":10,"ignore_whitespace":"IGNORE_ALL","intraline_difference":true,"line_length":100,"cursor_blink_rate":500,"show_line_endings":true,"show_tabs":true,"show_whitespace_errors":true,"syntax_highlighting":true,"tab_size":8,"font_size":12} // DiffPreferencesInfo | 
            //val result : DiffPreferencesInfo = apiInstance.putAccountsAccountIdPreferencesDiff(accountId, diffPreferencesInfo)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdPreferencesEdit
        should("test putAccountsAccountIdPreferencesEdit") {
            // uncomment below to test putAccountsAccountIdPreferencesEdit
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val editPreferencesInfo : EditPreferencesInfo = {"tab_size":4,"line_length":80,"indent_unit":2,"cursor_blink_rate":530,"hide_top_menu":true,"show_tabs":true,"show_whitespace_errors":true,"syntax_highlighting":true,"hide_line_numbers":true,"match_brackets":true,"line_wrapping":false,"auto_close_brackets":true} // EditPreferencesInfo | 
            //val result : EditPreferencesInfo = apiInstance.putAccountsAccountIdPreferencesEdit(accountId, editPreferencesInfo)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdStarredChangesStarredChangeId
        should("test putAccountsAccountIdStarredChangesStarredChangeId") {
            // uncomment below to test putAccountsAccountIdStarredChangesStarredChangeId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val starredChangeId : kotlin.String = starredChangeId_example // kotlin.String | 
            //apiInstance.putAccountsAccountIdStarredChangesStarredChangeId(accountId, starredChangeId)
        }

        // to test putAccountsAccountIdStatus
        should("test putAccountsAccountIdStatus") {
            // uncomment below to test putAccountsAccountIdStatus
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val statusInput : StatusInput = {"status":"Out Of Office"} // StatusInput | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdStatus(accountId, statusInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdTokensTokenId
        should("test putAccountsAccountIdTokensTokenId") {
            // uncomment below to test putAccountsAccountIdTokensTokenId
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val tokenId : kotlin.String = tokenId_example // kotlin.String | 
            //val authTokenInput : AuthTokenInput = {"id":"example","token":"secret_token_123","lifetime":"30d"} // AuthTokenInput | 
            //val result : AuthTokenInfo = apiInstance.putAccountsAccountIdTokensTokenId(accountId, tokenId, authTokenInput)
            //result shouldBe ("TODO")
        }

        // to test putAccountsAccountIdUsername
        should("test putAccountsAccountIdUsername") {
            // uncomment below to test putAccountsAccountIdUsername
            //val accountId : kotlin.String = accountId_example // kotlin.String | 
            //val usernameInput : UsernameInput = {"username":"jdoe"} // UsernameInput | 
            //val result : kotlin.String = apiInstance.putAccountsAccountIdUsername(accountId, usernameInput)
            //result shouldBe ("TODO")
        }

    }
}
