/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.google.gerrit.client.api.GroupsApi
import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.AddMembersInput
import com.google.gerrit.client.model.AddSubgroupsInput
import com.google.gerrit.client.model.CommonDescriptionInput
import com.google.gerrit.client.model.GroupAuditEventInfo
import com.google.gerrit.client.model.GroupInfo
import com.google.gerrit.client.model.GroupInput
import com.google.gerrit.client.model.GroupOptionsInfo
import com.google.gerrit.client.model.NameInput
import com.google.gerrit.client.model.OwnerInput

class GroupsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GroupsApi
        //val apiInstance = GroupsApi()

        // to test deleteGroupsGroupId
        should("test deleteGroupsGroupId") {
            // uncomment below to test deleteGroupsGroupId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.deleteGroupsGroupId(groupId)
            //result shouldBe ("TODO")
        }

        // to test deleteGroupsGroupIdDescription
        should("test deleteGroupsGroupIdDescription") {
            // uncomment below to test deleteGroupsGroupIdDescription
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.deleteGroupsGroupIdDescription(groupId)
            //result shouldBe ("TODO")
        }

        // to test deleteGroupsGroupIdGroupsSubgroupId
        should("test deleteGroupsGroupIdGroupsSubgroupId") {
            // uncomment below to test deleteGroupsGroupIdGroupsSubgroupId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val subgroupId : kotlin.String = subgroupId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.deleteGroupsGroupIdGroupsSubgroupId(groupId, subgroupId)
            //result shouldBe ("TODO")
        }

        // to test deleteGroupsGroupIdMembersMemberId
        should("test deleteGroupsGroupIdMembersMemberId") {
            // uncomment below to test deleteGroupsGroupIdMembersMemberId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val memberId : kotlin.String = memberId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.deleteGroupsGroupIdMembersMemberId(groupId, memberId)
            //result shouldBe ("TODO")
        }

        // to test getGroups
        should("test getGroups") {
            // uncomment below to test getGroups
            //val result : kotlin.Any = apiInstance.getGroups()
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupId
        should("test getGroupsGroupId") {
            // uncomment below to test getGroupsGroupId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : GroupInfo = apiInstance.getGroupsGroupId(groupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdDescription
        should("test getGroupsGroupIdDescription") {
            // uncomment below to test getGroupsGroupIdDescription
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.getGroupsGroupIdDescription(groupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdDetail
        should("test getGroupsGroupIdDetail") {
            // uncomment below to test getGroupsGroupIdDetail
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : GroupInfo = apiInstance.getGroupsGroupIdDetail(groupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdGroups
        should("test getGroupsGroupIdGroups") {
            // uncomment below to test getGroupsGroupIdGroups
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : kotlin.collections.List<GroupInfo> = apiInstance.getGroupsGroupIdGroups(groupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdGroupsSubgroupId
        should("test getGroupsGroupIdGroupsSubgroupId") {
            // uncomment below to test getGroupsGroupIdGroupsSubgroupId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val subgroupId : kotlin.String = subgroupId_example // kotlin.String | 
            //val result : GroupInfo = apiInstance.getGroupsGroupIdGroupsSubgroupId(groupId, subgroupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdLogAudit
        should("test getGroupsGroupIdLogAudit") {
            // uncomment below to test getGroupsGroupIdLogAudit
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : kotlin.collections.List<GroupAuditEventInfo> = apiInstance.getGroupsGroupIdLogAudit(groupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdMembers
        should("test getGroupsGroupIdMembers") {
            // uncomment below to test getGroupsGroupIdMembers
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val recursive : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.collections.List<AccountInfo> = apiInstance.getGroupsGroupIdMembers(groupId, recursive)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdMembersMemberId
        should("test getGroupsGroupIdMembersMemberId") {
            // uncomment below to test getGroupsGroupIdMembersMemberId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val memberId : kotlin.String = memberId_example // kotlin.String | 
            //val result : AccountInfo = apiInstance.getGroupsGroupIdMembersMemberId(groupId, memberId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdName
        should("test getGroupsGroupIdName") {
            // uncomment below to test getGroupsGroupIdName
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.getGroupsGroupIdName(groupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdOptions
        should("test getGroupsGroupIdOptions") {
            // uncomment below to test getGroupsGroupIdOptions
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : GroupOptionsInfo = apiInstance.getGroupsGroupIdOptions(groupId)
            //result shouldBe ("TODO")
        }

        // to test getGroupsGroupIdOwner
        should("test getGroupsGroupIdOwner") {
            // uncomment below to test getGroupsGroupIdOwner
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : GroupInfo = apiInstance.getGroupsGroupIdOwner(groupId)
            //result shouldBe ("TODO")
        }

        // to test postGroupsGroupIdGroups
        should("test postGroupsGroupIdGroups") {
            // uncomment below to test postGroupsGroupIdGroups
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val addSubgroupsInput : AddSubgroupsInput =  // AddSubgroupsInput | 
            //val result : kotlin.collections.List<GroupInfo> = apiInstance.postGroupsGroupIdGroups(groupId, addSubgroupsInput)
            //result shouldBe ("TODO")
        }

        // to test postGroupsGroupIdGroupsAdd
        should("test postGroupsGroupIdGroupsAdd") {
            // uncomment below to test postGroupsGroupIdGroupsAdd
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val addSubgroupsInput : AddSubgroupsInput = {"groups":["MyGroup","MyOtherGroup"]} // AddSubgroupsInput | 
            //val result : kotlin.collections.List<GroupInfo> = apiInstance.postGroupsGroupIdGroupsAdd(groupId, addSubgroupsInput)
            //result shouldBe ("TODO")
        }

        // to test postGroupsGroupIdGroupsDelete
        should("test postGroupsGroupIdGroupsDelete") {
            // uncomment below to test postGroupsGroupIdGroupsDelete
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val addSubgroupsInput : AddSubgroupsInput = {groups=[MyGroup, MyOtherGroup]} // AddSubgroupsInput | 
            //apiInstance.postGroupsGroupIdGroupsDelete(groupId, addSubgroupsInput)
        }

        // to test postGroupsGroupIdIndex
        should("test postGroupsGroupIdIndex") {
            // uncomment below to test postGroupsGroupIdIndex
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //apiInstance.postGroupsGroupIdIndex(groupId)
        }

        // to test postGroupsGroupIdMembers
        should("test postGroupsGroupIdMembers") {
            // uncomment below to test postGroupsGroupIdMembers
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val addMembersInput : AddMembersInput =  // AddMembersInput | 
            //val result : kotlin.collections.List<AccountInfo> = apiInstance.postGroupsGroupIdMembers(groupId, addMembersInput)
            //result shouldBe ("TODO")
        }

        // to test postGroupsGroupIdMembersAdd
        should("test postGroupsGroupIdMembersAdd") {
            // uncomment below to test postGroupsGroupIdMembersAdd
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val addMembersInput : AddMembersInput = {"members":["jane.roe@example.com","john.doe@example.com"]} // AddMembersInput | 
            //val result : kotlin.collections.List<AccountInfo> = apiInstance.postGroupsGroupIdMembersAdd(groupId, addMembersInput)
            //result shouldBe ("TODO")
        }

        // to test postGroupsGroupIdMembersDelete
        should("test postGroupsGroupIdMembersDelete") {
            // uncomment below to test postGroupsGroupIdMembersDelete
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val addMembersInput : AddMembersInput = {members=[jane.roe@example.com, john.doe@example.com]} // AddMembersInput | 
            //apiInstance.postGroupsGroupIdMembersDelete(groupId, addMembersInput)
        }

        // to test putGroupsGroupId
        should("test putGroupsGroupId") {
            // uncomment below to test putGroupsGroupId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val groupInput : GroupInput = {"description":"contains all committers for MyProject","visible_to_all":true,"owner":"MyProject-Owners","owner_id":"7ca042f4d5847936fcb90ca91057673157fd06fc"} // GroupInput | 
            //val result : GroupInfo = apiInstance.putGroupsGroupId(groupId, groupInput)
            //result shouldBe ("TODO")
        }

        // to test putGroupsGroupIdDescription
        should("test putGroupsGroupIdDescription") {
            // uncomment below to test putGroupsGroupIdDescription
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val commonDescriptionInput : CommonDescriptionInput = {"description":"The committers of MyProject."} // CommonDescriptionInput | 
            //val result : kotlin.String = apiInstance.putGroupsGroupIdDescription(groupId, commonDescriptionInput)
            //result shouldBe ("TODO")
        }

        // to test putGroupsGroupIdGroupsSubgroupId
        should("test putGroupsGroupIdGroupsSubgroupId") {
            // uncomment below to test putGroupsGroupIdGroupsSubgroupId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val subgroupId : kotlin.String = subgroupId_example // kotlin.String | 
            //val addSubgroupsInput : AddSubgroupsInput =  // AddSubgroupsInput | 
            //val result : GroupInfo = apiInstance.putGroupsGroupIdGroupsSubgroupId(groupId, subgroupId, addSubgroupsInput)
            //result shouldBe ("TODO")
        }

        // to test putGroupsGroupIdMembersMemberId
        should("test putGroupsGroupIdMembersMemberId") {
            // uncomment below to test putGroupsGroupIdMembersMemberId
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val memberId : kotlin.String = memberId_example // kotlin.String | 
            //val addMembersInput : AddMembersInput =  // AddMembersInput | 
            //val result : AccountInfo = apiInstance.putGroupsGroupIdMembersMemberId(groupId, memberId, addMembersInput)
            //result shouldBe ("TODO")
        }

        // to test putGroupsGroupIdName
        should("test putGroupsGroupIdName") {
            // uncomment below to test putGroupsGroupIdName
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val nameInput : NameInput = {"name":"My-Project-Committers"} // NameInput | 
            //val result : kotlin.String = apiInstance.putGroupsGroupIdName(groupId, nameInput)
            //result shouldBe ("TODO")
        }

        // to test putGroupsGroupIdOptions
        should("test putGroupsGroupIdOptions") {
            // uncomment below to test putGroupsGroupIdOptions
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val groupOptionsInfo : GroupOptionsInfo = {"visible_to_all":true} // GroupOptionsInfo | 
            //val result : GroupOptionsInfo = apiInstance.putGroupsGroupIdOptions(groupId, groupOptionsInfo)
            //result shouldBe ("TODO")
        }

        // to test putGroupsGroupIdOwner
        should("test putGroupsGroupIdOwner") {
            // uncomment below to test putGroupsGroupIdOwner
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val ownerInput : OwnerInput = {"owner":"6a1e70e1a88782771a91808c8af9bbb7a9871389"} // OwnerInput | 
            //val result : GroupInfo = apiInstance.putGroupsGroupIdOwner(groupId, ownerInput)
            //result shouldBe ("TODO")
        }

    }
}
