/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.google.gerrit.client.model.ProjectAccessInfo

import com.google.gson.annotations.SerializedName

import com.google.gerrit.client.infrastructure.ApiClient
import com.google.gerrit.client.infrastructure.ApiResponse
import com.google.gerrit.client.infrastructure.ClientException
import com.google.gerrit.client.infrastructure.ClientError
import com.google.gerrit.client.infrastructure.ServerException
import com.google.gerrit.client.infrastructure.ServerError
import com.google.gerrit.client.infrastructure.MultiValueMap
import com.google.gerrit.client.infrastructure.PartConfig
import com.google.gerrit.client.infrastructure.RequestConfig
import com.google.gerrit.client.infrastructure.RequestMethod
import com.google.gerrit.client.infrastructure.ResponseType
import com.google.gerrit.client.infrastructure.Success
import com.google.gerrit.client.infrastructure.toMultiValue

open class AccessApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://gerrit-review.googlesource.com")
        }
    }

    /**
     * GET /access
     * List access rights
     * Lists the access rights of one or more projects, named by the repeated project parameter.
     * @param project  (optional)
     * @return kotlin.collections.Map<kotlin.String, ProjectAccessInfo>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAccess(project: kotlin.collections.List<kotlin.String>? = null) : kotlin.collections.Map<kotlin.String, ProjectAccessInfo> {
        val localVarResponse = getAccessWithHttpInfo(project = project)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, ProjectAccessInfo>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access
     * List access rights
     * Lists the access rights of one or more projects, named by the repeated project parameter.
     * @param project  (optional)
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, ProjectAccessInfo>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getAccessWithHttpInfo(project: kotlin.collections.List<kotlin.String>?) : ApiResponse<kotlin.collections.Map<kotlin.String, ProjectAccessInfo>?> {
        val localVariableConfig = getAccessRequestConfig(project = project)

        return request<Unit, kotlin.collections.Map<kotlin.String, ProjectAccessInfo>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAccess
     *
     * @param project  (optional)
     * @return RequestConfig
     */
    fun getAccessRequestConfig(project: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (project != null) {
                    put("project", toMultiValue(project.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
