/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param message A clarifying message if status is not 200.
 * @param status The HTTP status code for the access. 200 means success and 403 means denied.
 * @param debugLogs Debug logs that may help to understand why a permission is denied or allowed.
 */


data class AccessCheckInfo (

    /* A clarifying message if status is not 200. */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* The HTTP status code for the access. 200 means success and 403 means denied. */
    @SerializedName("status")
    val status: kotlin.Int? = null,

    /* Debug logs that may help to understand why a permission is denied or allowed. */
    @SerializedName("debug_logs")
    val debugLogs: kotlin.collections.List<kotlin.String>? = null

) {


}

