/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AuthTokenInput

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param username 
 * @param name 
 * @param displayName 
 * @param email 
 * @param sshKey 
 * @param httpPassword 
 * @param tokens 
 * @param groups 
 */


data class AccountInput (

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("display_name")
    val displayName: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("ssh_key")
    val sshKey: kotlin.String? = null,

    @SerializedName("http_password")
    val httpPassword: kotlin.String? = null,

    @SerializedName("tokens")
    val tokens: kotlin.collections.List<AuthTokenInput>? = null,

    @SerializedName("groups")
    val groups: kotlin.collections.List<kotlin.String>? = null

) {


}

