/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param identity 
 * @param emailAddress 
 * @param trusted 
 * @param canDelete 
 */


data class AccountExternalIdInfo (

    @SerializedName("identity")
    val identity: kotlin.String? = null,

    @SerializedName("email_address")
    val emailAddress: kotlin.String? = null,

    @SerializedName("trusted")
    val trusted: kotlin.Boolean? = null,

    @SerializedName("can_delete")
    val canDelete: kotlin.Boolean? = null

) {


}

