/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param account 
 * @param lastUpdate 
 * @param reason 
 * @param reasonAccount 
 */


data class AttentionSetInfo (

    @SerializedName("account")
    val account: AccountInfo? = null,

    @SerializedName("last_update")
    val lastUpdate: kotlin.String? = null,

    @SerializedName("reason")
    val reason: kotlin.String? = null,

    @SerializedName("reason_account")
    val reasonAccount: AccountInfo? = null

) {


}

