/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.NotifyHandling
import com.google.gerrit.client.model.NotifyInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param user 
 * @param reason 
 * @param notify 
 * @param notifyDetails 
 */


data class AttentionSetInput (

    @SerializedName("user")
    val user: kotlin.String? = null,

    @SerializedName("reason")
    val reason: kotlin.String? = null,

    @SerializedName("notify")
    val notify: NotifyHandling? = null,

    @SerializedName("notify_details")
    val notifyDetails: kotlin.collections.Map<kotlin.String, NotifyInfo>? = null

) {


}

