/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id The id of the token.
 * @param token The token in plain text. Will only be returned once when creating the token.
 * @param expiration The timestamp at which the token will expire or has been expired. If null, token lifetime is unlimited.
 */


data class AuthTokenInfo (

    /* The id of the token. */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* The token in plain text. Will only be returned once when creating the token. */
    @SerializedName("token")
    val token: kotlin.String? = null,

    /* The timestamp at which the token will expire or has been expired. If null, token lifetime is unlimited. */
    @SerializedName("expiration")
    val expiration: kotlin.String? = null

) {


}

