/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fix 
 * @param branch 
 * @param skipCommits 
 * @param maxCommits 
 */


data class AutoCloseableChangesCheckInput (

    @SerializedName("fix")
    val fix: kotlin.Boolean? = null,

    @SerializedName("branch")
    val branch: kotlin.String? = null,

    @SerializedName("skip_commits")
    val skipCommits: kotlin.Int? = null,

    @SerializedName("max_commits")
    val maxCommits: kotlin.Int? = null

) {


}

