/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.RangeInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param author 
 * @param id 
 * @param time 
 * @param commitMsg 
 * @param ranges 
 */


data class BlameInfo (

    @SerializedName("author")
    val author: kotlin.String? = null,

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("time")
    val time: kotlin.Int? = null,

    @SerializedName("commit_msg")
    val commitMsg: kotlin.String? = null,

    @SerializedName("ranges")
    val ranges: kotlin.collections.List<RangeInfo>? = null

) {


}

