/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param revision The base revision of the new branch. + If not set and create_empty_commit is true the branch is created with an empty initial commit. + If not set and create_empty_commit is false or unset HEAD will be used as base revision.
 * @param createEmptyCommit Whether the branch should be created with an empty initial commit. + Cannot be used in combination with setting a revision. + Can be used to review the initial content of a branch (create the branch with an empty initial commit, make a second commit with the initial content, e.g.
 * @param ref The name of the branch. The prefix refs/heads/ can be omitted. + If set, must match the branch ID in the URL.
 * @param sourceRef The full name of the source ref where revision can be found. + Used when revision is not a ref name in order to check reachability from a specific ref. This ref should be visible to the caller. + If not set, then all visible refs under refs/heads/ and refs/tags/ are searched.
 * @param validationOptions Map with key-value pairs that are forwarded as options to the ref operation validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed ref operation validation listeners.
 */


data class BranchInput (

    /* The base revision of the new branch. + If not set and create_empty_commit is true the branch is created with an empty initial commit. + If not set and create_empty_commit is false or unset HEAD will be used as base revision. */
    @SerializedName("revision")
    val revision: kotlin.String? = null,

    /* Whether the branch should be created with an empty initial commit. + Cannot be used in combination with setting a revision. + Can be used to review the initial content of a branch (create the branch with an empty initial commit, make a second commit with the initial content, e.g. */
    @SerializedName("create_empty_commit")
    val createEmptyCommit: kotlin.Boolean? = null,

    /* The name of the branch. The prefix refs/heads/ can be omitted. + If set, must match the branch ID in the URL. */
    @SerializedName("ref")
    val ref: kotlin.String? = null,

    /* The full name of the source ref where revision can be found. + Used when revision is not a ref name in order to check reachability from a specific ref. This ref should be visible to the caller. + If not set, then all visible refs under refs/heads/ and refs/tags/ are searched. */
    @SerializedName("source_ref")
    val sourceRef: kotlin.String? = null,

    /* Map with key-value pairs that are forwarded as options to the ref operation validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed ref operation validation listeners. */
    @SerializedName("validation_options")
    val validationOptions: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

