/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.ActionInfo
import com.google.gerrit.client.model.WebLinkInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param actions 
 * @param webLinks Links to the branch in external sites as a list of WebLinkInfo entries.
 * @param ref The ref of the branch.
 * @param revision The revision to which the branch points.
 * @param canDelete Whether the calling user can delete this branch.
 */


data class BranchInfo (

    @SerializedName("actions")
    val actions: kotlin.collections.Map<kotlin.String, ActionInfo>? = null,

    /* Links to the branch in external sites as a list of WebLinkInfo entries. */
    @SerializedName("web_links")
    val webLinks: kotlin.collections.List<WebLinkInfo>? = null,

    /* The ref of the branch. */
    @SerializedName("ref")
    val ref: kotlin.String? = null,

    /* The revision to which the branch points. */
    @SerializedName("revision")
    val revision: kotlin.String? = null,

    /* Whether the calling user can delete this branch. */
    @SerializedName("can_delete")
    val canDelete: kotlin.Boolean? = null

) {


}

