/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.ActionInfo
import com.google.gerrit.client.model.AttentionSetInfo
import com.google.gerrit.client.model.ChangeMessageInfo
import com.google.gerrit.client.model.ChangeStatus
import com.google.gerrit.client.model.LabelInfo
import com.google.gerrit.client.model.LegacySubmitRequirementInfo
import com.google.gerrit.client.model.PluginDefinedInfo
import com.google.gerrit.client.model.ProblemInfo
import com.google.gerrit.client.model.ReviewerUpdateInfo
import com.google.gerrit.client.model.RevisionInfo
import com.google.gerrit.client.model.SubmitRecordInfo
import com.google.gerrit.client.model.SubmitRequirementResultInfo
import com.google.gerrit.client.model.SubmitType
import com.google.gerrit.client.model.TrackingIdInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param tripletId 
 * @param project 
 * @param branch 
 * @param fullBranch 
 * @param topic 
 * @param attentionSet 
 * @param removedFromAttentionSet 
 * @param customKeyedValues 
 * @param hashtags 
 * @param changeId 
 * @param subject 
 * @param status 
 * @param created 
 * @param updated 
 * @param submitted 
 * @param submitter 
 * @param starred 
 * @param stars 
 * @param reviewed 
 * @param submitType 
 * @param mergeable 
 * @param submittable 
 * @param insertions 
 * @param deletions 
 * @param totalCommentCount 
 * @param unresolvedCommentCount 
 * @param isPrivate 
 * @param workInProgress 
 * @param hasReviewStarted 
 * @param revertOf 
 * @param submissionId 
 * @param cherryPickOfChange 
 * @param cherryPickOfPatchSet 
 * @param metaRevId 
 * @param containsGitConflicts 
 * @param number 
 * @param virtualIdNumber 
 * @param owner 
 * @param actions 
 * @param labels 
 * @param permittedLabels 
 * @param removableLabels 
 * @param removableReviewers 
 * @param reviewers 
 * @param pendingReviewers 
 * @param reviewerUpdates 
 * @param messages 
 * @param currentRevisionNumber 
 * @param currentRevision 
 * @param revisions 
 * @param moreChanges 
 * @param problems 
 * @param plugins 
 * @param trackingIds 
 * @param requirements 
 * @param submitRecords 
 * @param submitRequirements 
 */


data class ChangeInfo (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("triplet_id")
    val tripletId: kotlin.String? = null,

    @SerializedName("project")
    val project: kotlin.String? = null,

    @SerializedName("branch")
    val branch: kotlin.String? = null,

    @SerializedName("full_branch")
    val fullBranch: kotlin.String? = null,

    @SerializedName("topic")
    val topic: kotlin.String? = null,

    @SerializedName("attention_set")
    val attentionSet: kotlin.collections.Map<kotlin.String, AttentionSetInfo>? = null,

    @SerializedName("removed_from_attention_set")
    val removedFromAttentionSet: kotlin.collections.Map<kotlin.String, AttentionSetInfo>? = null,

    @SerializedName("custom_keyed_values")
    val customKeyedValues: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerializedName("hashtags")
    val hashtags: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("change_id")
    val changeId: kotlin.String? = null,

    @SerializedName("subject")
    val subject: kotlin.String? = null,

    @SerializedName("status")
    val status: ChangeStatus? = null,

    @SerializedName("created")
    val created: kotlin.String? = null,

    @SerializedName("updated")
    val updated: kotlin.String? = null,

    @SerializedName("submitted")
    val submitted: kotlin.String? = null,

    @SerializedName("submitter")
    val submitter: AccountInfo? = null,

    @SerializedName("starred")
    val starred: kotlin.Boolean? = null,

    @SerializedName("stars")
    val stars: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("reviewed")
    val reviewed: kotlin.Boolean? = null,

    @SerializedName("submit_type")
    val submitType: SubmitType? = null,

    @SerializedName("mergeable")
    val mergeable: kotlin.Boolean? = null,

    @SerializedName("submittable")
    val submittable: kotlin.Boolean? = null,

    @SerializedName("insertions")
    val insertions: kotlin.Int? = null,

    @SerializedName("deletions")
    val deletions: kotlin.Int? = null,

    @SerializedName("total_comment_count")
    val totalCommentCount: kotlin.Int? = null,

    @SerializedName("unresolved_comment_count")
    val unresolvedCommentCount: kotlin.Int? = null,

    @SerializedName("is_private")
    val isPrivate: kotlin.Boolean? = null,

    @SerializedName("work_in_progress")
    val workInProgress: kotlin.Boolean? = null,

    @SerializedName("has_review_started")
    val hasReviewStarted: kotlin.Boolean? = null,

    @SerializedName("revert_of")
    val revertOf: kotlin.Int? = null,

    @SerializedName("submission_id")
    val submissionId: kotlin.String? = null,

    @SerializedName("cherry_pick_of_change")
    val cherryPickOfChange: kotlin.Int? = null,

    @SerializedName("cherry_pick_of_patch_set")
    val cherryPickOfPatchSet: kotlin.Int? = null,

    @SerializedName("meta_rev_id")
    val metaRevId: kotlin.String? = null,

    @SerializedName("contains_git_conflicts")
    val containsGitConflicts: kotlin.Boolean? = null,

    @SerializedName("_number")
    val number: kotlin.Int? = null,

    @SerializedName("virtual_id_number")
    val virtualIdNumber: kotlin.Int? = null,

    @SerializedName("owner")
    val owner: AccountInfo? = null,

    @SerializedName("actions")
    val actions: kotlin.collections.Map<kotlin.String, ActionInfo>? = null,

    @SerializedName("labels")
    val labels: kotlin.collections.Map<kotlin.String, LabelInfo>? = null,

    @SerializedName("permitted_labels")
    val permittedLabels: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null,

    @SerializedName("removable_labels")
    val removableLabels: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, kotlin.collections.List<AccountInfo>>>? = null,

    @SerializedName("removable_reviewers")
    val removableReviewers: kotlin.collections.List<AccountInfo>? = null,

    @SerializedName("reviewers")
    val reviewers: kotlin.collections.Map<kotlin.String, kotlin.collections.List<AccountInfo>>? = null,

    @SerializedName("pending_reviewers")
    val pendingReviewers: kotlin.collections.Map<kotlin.String, kotlin.collections.List<AccountInfo>>? = null,

    @SerializedName("reviewer_updates")
    val reviewerUpdates: kotlin.collections.List<ReviewerUpdateInfo>? = null,

    @SerializedName("messages")
    val messages: kotlin.collections.List<ChangeMessageInfo>? = null,

    @SerializedName("current_revision_number")
    val currentRevisionNumber: kotlin.Int? = null,

    @SerializedName("current_revision")
    val currentRevision: kotlin.String? = null,

    @SerializedName("revisions")
    val revisions: kotlin.collections.Map<kotlin.String, RevisionInfo>? = null,

    @SerializedName("_more_changes")
    val moreChanges: kotlin.Boolean? = null,

    @SerializedName("problems")
    val problems: kotlin.collections.List<ProblemInfo>? = null,

    @SerializedName("plugins")
    val plugins: kotlin.collections.List<PluginDefinedInfo>? = null,

    @SerializedName("tracking_ids")
    val trackingIds: kotlin.collections.List<TrackingIdInfo>? = null,

    @SerializedName("requirements")
    val requirements: kotlin.collections.List<LegacySubmitRequirementInfo>? = null,

    @SerializedName("submit_records")
    val submitRecords: kotlin.collections.List<SubmitRecordInfo>? = null,

    @SerializedName("submit_requirements")
    val submitRequirements: kotlin.collections.List<SubmitRequirementResultInfo>? = null

) {


}

