/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInput
import com.google.gerrit.client.model.ApplyPatchInput
import com.google.gerrit.client.model.ChangeStatus
import com.google.gerrit.client.model.ListChangesOption
import com.google.gerrit.client.model.MergeInput
import com.google.gerrit.client.model.NotifyHandling
import com.google.gerrit.client.model.NotifyInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param project 
 * @param branch 
 * @param subject 
 * @param topic 
 * @param status 
 * @param isPrivate 
 * @param workInProgress 
 * @param baseChange 
 * @param baseCommit 
 * @param newBranch 
 * @param validationOptions 
 * @param customKeyedValues 
 * @param merge 
 * @param patch 
 * @param author 
 * @param responseFormatOptions 
 * @param notify 
 * @param notifyDetails 
 */


data class ChangeInput (

    @SerializedName("project")
    val project: kotlin.String? = null,

    @SerializedName("branch")
    val branch: kotlin.String? = null,

    @SerializedName("subject")
    val subject: kotlin.String? = null,

    @SerializedName("topic")
    val topic: kotlin.String? = null,

    @SerializedName("status")
    val status: ChangeStatus? = null,

    @SerializedName("is_private")
    val isPrivate: kotlin.Boolean? = null,

    @SerializedName("work_in_progress")
    val workInProgress: kotlin.Boolean? = null,

    @SerializedName("base_change")
    val baseChange: kotlin.String? = null,

    @SerializedName("base_commit")
    val baseCommit: kotlin.String? = null,

    @SerializedName("new_branch")
    val newBranch: kotlin.Boolean? = null,

    @SerializedName("validation_options")
    val validationOptions: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerializedName("custom_keyed_values")
    val customKeyedValues: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerializedName("merge")
    val merge: MergeInput? = null,

    @SerializedName("patch")
    val patch: ApplyPatchInput? = null,

    @SerializedName("author")
    val author: AccountInput? = null,

    @SerializedName("response_format_options")
    val responseFormatOptions: kotlin.collections.List<ListChangesOption>? = null,

    @SerializedName("notify")
    val notify: NotifyHandling? = null,

    @SerializedName("notify_details")
    val notifyDetails: kotlin.collections.Map<kotlin.String, NotifyInfo>? = null

) {


}

