/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param tag 
 * @param author 
 * @param realAuthor 
 * @param date 
 * @param message 
 * @param accountsInMessage 
 * @param revisionNumber 
 */


data class ChangeMessageInfo (

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("tag")
    val tag: kotlin.String? = null,

    @SerializedName("author")
    val author: AccountInfo? = null,

    @SerializedName("real_author")
    val realAuthor: AccountInfo? = null,

    @SerializedName("date")
    val date: kotlin.String? = null,

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("accounts_in_message")
    val accountsInMessage: kotlin.collections.List<AccountInfo>? = null,

    @SerializedName("_revision_number")
    val revisionNumber: kotlin.Int? = null

) {


}

