/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param allowBlame 
 * @param disablePrivateChanges 
 * @param updateDelay 
 * @param submitWholeTopic 
 * @param mergeabilityComputationBehavior 
 * @param conflictsPredicateEnabled 
 * @param allowMarkdownBase64ImagesInComments 
 */


data class ChangeConfigInfo (

    @SerializedName("allow_blame")
    val allowBlame: kotlin.Boolean? = null,

    @SerializedName("disable_private_changes")
    val disablePrivateChanges: kotlin.Boolean? = null,

    @SerializedName("update_delay")
    val updateDelay: kotlin.Int? = null,

    @SerializedName("submit_whole_topic")
    val submitWholeTopic: kotlin.Boolean? = null,

    @SerializedName("mergeability_computation_behavior")
    val mergeabilityComputationBehavior: kotlin.String? = null,

    @SerializedName("conflicts_predicate_enabled")
    val conflictsPredicateEnabled: kotlin.Boolean? = null,

    @SerializedName("allow_markdown_base64_images_in_comments")
    val allowMarkdownBase64ImagesInComments: kotlin.Boolean? = null

) {


}

