/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: REWORK,TRIVIAL_REBASE,TRIVIAL_REBASE_WITH_MESSAGE_UPDATE,MERGE_FIRST_PARENT_UPDATE,NO_CODE_CHANGE,NO_CHANGE
 */

enum class ChangeKind(val value: kotlin.String) {

    @SerializedName(value = "REWORK")
    REWORK("REWORK"),

    @SerializedName(value = "TRIVIAL_REBASE")
    TRIVIAL_REBASE("TRIVIAL_REBASE"),

    @SerializedName(value = "TRIVIAL_REBASE_WITH_MESSAGE_UPDATE")
    TRIVIAL_REBASE_WITH_MESSAGE_UPDATE("TRIVIAL_REBASE_WITH_MESSAGE_UPDATE"),

    @SerializedName(value = "MERGE_FIRST_PARENT_UPDATE")
    MERGE_FIRST_PARENT_UPDATE("MERGE_FIRST_PARENT_UPDATE"),

    @SerializedName(value = "NO_CODE_CHANGE")
    NO_CODE_CHANGE("NO_CODE_CHANGE"),

    @SerializedName(value = "NO_CHANGE")
    NO_CHANGE("NO_CHANGE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ChangeKind) "$data" else null

        /**
         * Returns a valid [ChangeKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ChangeKind? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

