/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param match 
 * @param link 
 * @param prefix 
 * @param suffix 
 * @param text 
 * @param enabled 
 */


data class CommentLinkInfo (

    @SerializedName("match")
    val match: kotlin.String? = null,

    @SerializedName("link")
    val link: kotlin.String? = null,

    @SerializedName("prefix")
    val prefix: kotlin.String? = null,

    @SerializedName("suffix")
    val suffix: kotlin.String? = null,

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("enabled")
    val enabled: kotlin.Boolean? = null

) {


}

