/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status 
 * @param oldMode 
 * @param newMode 
 * @param oldSha 
 * @param newSha 
 * @param binary 
 * @param oldPath 
 * @param linesInserted 
 * @param linesDeleted 
 * @param sizeDelta 
 * @param propertySize 
 * @param diffsTooExpensiveToCompute 
 */


data class CommonFileInfo (

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("old_mode")
    val oldMode: kotlin.Int? = null,

    @SerializedName("new_mode")
    val newMode: kotlin.Int? = null,

    @SerializedName("old_sha")
    val oldSha: kotlin.String? = null,

    @SerializedName("new_sha")
    val newSha: kotlin.String? = null,

    @SerializedName("binary")
    val binary: kotlin.Boolean? = null,

    @SerializedName("old_path")
    val oldPath: kotlin.String? = null,

    @SerializedName("lines_inserted")
    val linesInserted: kotlin.Int? = null,

    @SerializedName("lines_deleted")
    val linesDeleted: kotlin.Int? = null,

    @SerializedName("size_delta")
    val sizeDelta: kotlin.Int? = null,

    @SerializedName("size")
    val propertySize: kotlin.Int? = null,

    @SerializedName("diffs_too_expensive_to_compute")
    val diffsTooExpensiveToCompute: kotlin.Boolean? = null

) {


}

