/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.ActionInfo
import com.google.gerrit.client.model.CommentLinkInfo
import com.google.gerrit.client.model.ConfigParameterInfo
import com.google.gerrit.client.model.InheritedBooleanInfo
import com.google.gerrit.client.model.MaxObjectSizeLimitInfo
import com.google.gerrit.client.model.ProjectState
import com.google.gerrit.client.model.SubmitType
import com.google.gerrit.client.model.SubmitTypeInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param description The description of the project.
 * @param useContributorAgreements InheritedBooleanInfo that tells whether authors must complete a contributor agreement on the site before pushing any commits or changes to this project.
 * @param useContentMerge InheritedBooleanInfo that tells whether Gerrit will try to perform a 3-way merge of text file content when a file has been modified by both the destination branch and the change being submitted. This option only takes effect if submit type is not FAST_FORWARD_ONLY.
 * @param useSignedOffBy InheritedBooleanInfo that tells whether each change must contain a Signed-off-by line from either the author or the uploader in the commit message.
 * @param createNewChangeForAllNotInTarget InheritedBooleanInfo that tells whether a new change is created for every commit not in target branch.
 * @param requireChangeId InheritedBooleanInfo that tells whether a valid Change-Id footer in any commit uploaded for review is required. This does not apply to commits pushed directly to a branch or tag. This property is deprecated and will be removed in a future release.
 * @param enableSignedPush InheritedBooleanInfo that tells whether signed push validation is enabled on the project.
 * @param requireSignedPush InheritedBooleanInfo that tells whether signed push validation is required on the project.
 * @param rejectImplicitMerges InheritedBooleanInfo that tells whether implicit merges should be rejected on changes pushed to or submitted in the project.
 * @param privateByDefault InheritedBooleanInfo that tells whether all new changes are set as private by default.
 * @param workInProgressByDefault InheritedBooleanInfo that tells whether all new changes are set as work-in-progress by default.
 * @param enableReviewerByEmail 
 * @param matchAuthorToCommitterDate InheritedBooleanInfo that indicates whether a change's author date will be changed to match its submitter date upon submit.
 * @param rejectEmptyCommit InheritedBooleanInfo that tells whether empty commits should be rejected when a change is merged. ActionInfo entities.
 * @param skipAddingAuthorAndCommitterAsReviewers Whether to skip adding the Git commit author and committer as reviewers for a new change.
 * @param maxObjectSizeLimit The max object size limit of this project as a MaxObjectSizeLimitInfo entity.
 * @param submitType Deprecated; equivalent to value in default_submit_type.
 * @param defaultSubmitType SubmitTypeInfo that describes the default submit type of the project, when not overridden at the change level.
 * @param state The state of the project, can be ACTIVE, READ_ONLY or HIDDEN. + Not set if the project state is ACTIVE.
 * @param pluginConfig Plugin configuration as map which maps the plugin name to a map of parameter names to ConfigParameterInfo entities. Only filled for users who have read access to refs/meta/config.
 * @param actions Actions the caller might be able to perform on this project. The information is a map of view names to
 * @param commentlinks Map with the comment link configurations of the project. The name of the comment link configuration is mapped to a CommentlinkInfo entity.
 * @param extensionPanelNames 
 */


data class ConfigInfo (

    /* The description of the project. */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* InheritedBooleanInfo that tells whether authors must complete a contributor agreement on the site before pushing any commits or changes to this project. */
    @SerializedName("use_contributor_agreements")
    val useContributorAgreements: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether Gerrit will try to perform a 3-way merge of text file content when a file has been modified by both the destination branch and the change being submitted. This option only takes effect if submit type is not FAST_FORWARD_ONLY. */
    @SerializedName("use_content_merge")
    val useContentMerge: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether each change must contain a Signed-off-by line from either the author or the uploader in the commit message. */
    @SerializedName("use_signed_off_by")
    val useSignedOffBy: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether a new change is created for every commit not in target branch. */
    @SerializedName("create_new_change_for_all_not_in_target")
    val createNewChangeForAllNotInTarget: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether a valid Change-Id footer in any commit uploaded for review is required. This does not apply to commits pushed directly to a branch or tag. This property is deprecated and will be removed in a future release. */
    @SerializedName("require_change_id")
    val requireChangeId: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether signed push validation is enabled on the project. */
    @SerializedName("enable_signed_push")
    val enableSignedPush: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether signed push validation is required on the project. */
    @SerializedName("require_signed_push")
    val requireSignedPush: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether implicit merges should be rejected on changes pushed to or submitted in the project. */
    @SerializedName("reject_implicit_merges")
    val rejectImplicitMerges: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether all new changes are set as private by default. */
    @SerializedName("private_by_default")
    val privateByDefault: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether all new changes are set as work-in-progress by default. */
    @SerializedName("work_in_progress_by_default")
    val workInProgressByDefault: InheritedBooleanInfo? = null,

    @SerializedName("enable_reviewer_by_email")
    val enableReviewerByEmail: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that indicates whether a change's author date will be changed to match its submitter date upon submit. */
    @SerializedName("match_author_to_committer_date")
    val matchAuthorToCommitterDate: InheritedBooleanInfo? = null,

    /* InheritedBooleanInfo that tells whether empty commits should be rejected when a change is merged. ActionInfo entities. */
    @SerializedName("reject_empty_commit")
    val rejectEmptyCommit: InheritedBooleanInfo? = null,

    /* Whether to skip adding the Git commit author and committer as reviewers for a new change. */
    @SerializedName("skip_adding_author_and_committer_as_reviewers")
    val skipAddingAuthorAndCommitterAsReviewers: InheritedBooleanInfo? = null,

    /* The max object size limit of this project as a MaxObjectSizeLimitInfo entity. */
    @SerializedName("max_object_size_limit")
    val maxObjectSizeLimit: MaxObjectSizeLimitInfo? = null,

    /* Deprecated; equivalent to value in default_submit_type. */
    @SerializedName("submit_type")
    val submitType: SubmitType? = null,

    /* SubmitTypeInfo that describes the default submit type of the project, when not overridden at the change level. */
    @SerializedName("default_submit_type")
    val defaultSubmitType: SubmitTypeInfo? = null,

    /* The state of the project, can be ACTIVE, READ_ONLY or HIDDEN. + Not set if the project state is ACTIVE. */
    @SerializedName("state")
    val state: ProjectState? = null,

    /* Plugin configuration as map which maps the plugin name to a map of parameter names to ConfigParameterInfo entities. Only filled for users who have read access to refs/meta/config. */
    @SerializedName("plugin_config")
    val pluginConfig: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, ConfigParameterInfo>>? = null,

    /* Actions the caller might be able to perform on this project. The information is a map of view names to */
    @SerializedName("actions")
    val actions: kotlin.collections.Map<kotlin.String, ActionInfo>? = null,

    /* Map with the comment link configurations of the project. The name of the comment link configuration is mapped to a CommentlinkInfo entity. */
    @SerializedName("commentlinks")
    val commentlinks: kotlin.collections.Map<kotlin.String, CommentLinkInfo>? = null,

    @SerializedName("extension_panel_names")
    val extensionPanelNames: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null

) {


}

