/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lineNumber The line number of the source line.
 * @param contextLine The text of the context line.
 */


data class ContextLineInfo (

    /* The line number of the source line. */
    @SerializedName("line_number")
    val lineNumber: kotlin.Int? = null,

    /* The text of the context line. */
    @SerializedName("context_line")
    val contextLine: kotlin.String? = null

) {


}

