/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.FileChange

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commitMessage 
 * @param baseRevision 
 * @param files 
 * @param validationOptions 
 */


data class CreateCommitInput (

    @SerializedName("commit_message")
    val commitMessage: kotlin.String? = null,

    @SerializedName("base_revision")
    val baseRevision: kotlin.String? = null,

    @SerializedName("files")
    val files: kotlin.collections.Map<kotlin.String, FileChange>? = null,

    @SerializedName("validation_options")
    val validationOptions: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

