/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param reason The reason why the change message should be deleted. + If set, the change message will be replaced with \"Change message removed by: name\\nReason: reason\", or just \"Change message removed by: name.\" if not set.
 */


data class DeleteChangeMessageInput (

    /* The reason why the change message should be deleted. + If set, the change message will be replaced with \"Change message removed by: name\\nReason: reason\", or just \"Change message removed by: name.\" if not set. */
    @SerializedName("reason")
    val reason: kotlin.String? = null

) {


}

