/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.ChangeInfo
import com.google.gerrit.client.model.CommentInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param change 
 * @param deleted 
 */


data class DeletedDraftCommentInfo (

    @SerializedName("change")
    val change: ChangeInfo? = null,

    @SerializedName("deleted")
    val deleted: kotlin.collections.List<CommentInfo>? = null

) {


}

