/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.ResponsiveMode
import com.google.gerrit.client.model.Whitespace

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param context 
 * @param tabSize 
 * @param fontSize 
 * @param lineLength 
 * @param cursorBlinkRate 
 * @param expandAllComments 
 * @param intralineDifference 
 * @param manualReview 
 * @param showLineEndings 
 * @param showTabs 
 * @param showWhitespaceErrors 
 * @param syntaxHighlighting 
 * @param hideTopMenu 
 * @param autoHideDiffTableHeader 
 * @param hideLineNumbers 
 * @param renderEntireFile 
 * @param hideEmptyPane 
 * @param matchBrackets 
 * @param lineWrapping 
 * @param responsiveMode 
 * @param ignoreWhitespace 
 * @param retainHeader 
 * @param skipDeleted 
 * @param skipUnchanged 
 * @param skipUncommented 
 */


data class DiffPreferencesInfo (

    @SerializedName("context")
    val context: kotlin.Int? = null,

    @SerializedName("tab_size")
    val tabSize: kotlin.Int? = null,

    @SerializedName("font_size")
    val fontSize: kotlin.Int? = null,

    @SerializedName("line_length")
    val lineLength: kotlin.Int? = null,

    @SerializedName("cursor_blink_rate")
    val cursorBlinkRate: kotlin.Int? = null,

    @SerializedName("expand_all_comments")
    val expandAllComments: kotlin.Boolean? = null,

    @SerializedName("intraline_difference")
    val intralineDifference: kotlin.Boolean? = null,

    @SerializedName("manual_review")
    val manualReview: kotlin.Boolean? = null,

    @SerializedName("show_line_endings")
    val showLineEndings: kotlin.Boolean? = null,

    @SerializedName("show_tabs")
    val showTabs: kotlin.Boolean? = null,

    @SerializedName("show_whitespace_errors")
    val showWhitespaceErrors: kotlin.Boolean? = null,

    @SerializedName("syntax_highlighting")
    val syntaxHighlighting: kotlin.Boolean? = null,

    @SerializedName("hide_top_menu")
    val hideTopMenu: kotlin.Boolean? = null,

    @SerializedName("auto_hide_diff_table_header")
    val autoHideDiffTableHeader: kotlin.Boolean? = null,

    @SerializedName("hide_line_numbers")
    val hideLineNumbers: kotlin.Boolean? = null,

    @SerializedName("render_entire_file")
    val renderEntireFile: kotlin.Boolean? = null,

    @SerializedName("hide_empty_pane")
    val hideEmptyPane: kotlin.Boolean? = null,

    @SerializedName("match_brackets")
    val matchBrackets: kotlin.Boolean? = null,

    @SerializedName("line_wrapping")
    val lineWrapping: kotlin.Boolean? = null,

    @SerializedName("responsive_mode")
    val responsiveMode: ResponsiveMode? = null,

    @SerializedName("ignore_whitespace")
    val ignoreWhitespace: Whitespace? = null,

    @SerializedName("retain_header")
    val retainHeader: kotlin.Boolean? = null,

    @SerializedName("skip_deleted")
    val skipDeleted: kotlin.Boolean? = null,

    @SerializedName("skip_unchanged")
    val skipUnchanged: kotlin.Boolean? = null,

    @SerializedName("skip_uncommented")
    val skipUncommented: kotlin.Boolean? = null

) {


}

