/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.DownloadSchemeInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param schemes 
 * @param archives 
 */


data class DownloadInfo (

    @SerializedName("schemes")
    val schemes: kotlin.collections.Map<kotlin.String, DownloadSchemeInfo>? = null,

    @SerializedName("archives")
    val archives: kotlin.collections.List<kotlin.String>? = null

) {


}

