/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param tabSize 
 * @param lineLength 
 * @param indentUnit 
 * @param cursorBlinkRate 
 * @param hideTopMenu 
 * @param showTabs 
 * @param showWhitespaceErrors 
 * @param syntaxHighlighting 
 * @param hideLineNumbers 
 * @param matchBrackets 
 * @param lineWrapping 
 * @param indentWithTabs 
 * @param autoCloseBrackets 
 * @param showBase 
 */


data class EditPreferencesInfo (

    @SerializedName("tab_size")
    val tabSize: kotlin.Int? = null,

    @SerializedName("line_length")
    val lineLength: kotlin.Int? = null,

    @SerializedName("indent_unit")
    val indentUnit: kotlin.Int? = null,

    @SerializedName("cursor_blink_rate")
    val cursorBlinkRate: kotlin.Int? = null,

    @SerializedName("hide_top_menu")
    val hideTopMenu: kotlin.Boolean? = null,

    @SerializedName("show_tabs")
    val showTabs: kotlin.Boolean? = null,

    @SerializedName("show_whitespace_errors")
    val showWhitespaceErrors: kotlin.Boolean? = null,

    @SerializedName("syntax_highlighting")
    val syntaxHighlighting: kotlin.Boolean? = null,

    @SerializedName("hide_line_numbers")
    val hideLineNumbers: kotlin.Boolean? = null,

    @SerializedName("match_brackets")
    val matchBrackets: kotlin.Boolean? = null,

    @SerializedName("line_wrapping")
    val lineWrapping: kotlin.Boolean? = null,

    @SerializedName("indent_with_tabs")
    val indentWithTabs: kotlin.Boolean? = null,

    @SerializedName("auto_close_brackets")
    val autoCloseBrackets: kotlin.Boolean? = null,

    @SerializedName("show_base")
    val showBase: kotlin.Boolean? = null

) {


}

