/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.CommitInfo
import com.google.gerrit.client.model.CommonFileInfo
import com.google.gerrit.client.model.FetchInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commit 
 * @param basePatchSetNumber 
 * @param baseRevision 
 * @param ref 
 * @param fetch 
 * @param files 
 * @param containsGitConflicts 
 */


data class EditInfo (

    @SerializedName("commit")
    val commit: CommitInfo? = null,

    @SerializedName("base_patch_set_number")
    val basePatchSetNumber: kotlin.Int? = null,

    @SerializedName("base_revision")
    val baseRevision: kotlin.String? = null,

    @SerializedName("ref")
    val ref: kotlin.String? = null,

    @SerializedName("fetch")
    val fetch: kotlin.collections.Map<kotlin.String, FetchInfo>? = null,

    @SerializedName("files")
    val files: kotlin.collections.Map<kotlin.String, CommonFileInfo>? = null,

    @SerializedName("contains_git_conflicts")
    val containsGitConflicts: kotlin.Boolean? = null

) {


}

