/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param email 
 * @param preferred 
 * @param avatar 
 * @param pendingConfirmation 
 */


data class EmailInfo (

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("preferred")
    val preferred: kotlin.Boolean? = null,

    @SerializedName("avatar")
    val avatar: kotlin.Boolean? = null,

    @SerializedName("pending_confirmation")
    val pendingConfirmation: kotlin.Boolean? = null

) {


}

