/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param content 
 * @param fileMode 
 * @param delete 
 * @param renameFrom 
 */


data class FileChange (

    @SerializedName("content")
    val content: kotlin.String? = null,

    @SerializedName("file_mode")
    val fileMode: kotlin.Int? = null,

    @SerializedName("delete")
    val delete: kotlin.Boolean? = null,

    @SerializedName("rename_from")
    val renameFrom: kotlin.String? = null

) {


}

