/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.WebLinkInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param contentType 
 * @param lines 
 * @param webLinks 
 */


data class FileMeta (

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("content_type")
    val contentType: kotlin.String? = null,

    @SerializedName("lines")
    val lines: kotlin.Int? = null,

    @SerializedName("web_links")
    val webLinks: kotlin.collections.List<WebLinkInfo>? = null

) {


}

