/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param deletePatchSetIfCommitMissing 
 * @param expectMergedAs 
 */


data class FixInput (

    @SerializedName("delete_patch_set_if_commit_missing")
    val deletePatchSetIfCommitMissing: kotlin.Boolean? = null,

    @SerializedName("expect_merged_as")
    val expectMergedAs: kotlin.String? = null

) {


}

