/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.Range

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param path 
 * @param range 
 * @param replacement 
 */


data class FixReplacementInfo (

    @SerializedName("path")
    val path: kotlin.String? = null,

    @SerializedName("range")
    val range: Range? = null,

    @SerializedName("replacement")
    val replacement: kotlin.String? = null

) {


}

