/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.FlowStageInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param uuid 
 * @param owner 
 * @param created 
 * @param stages 
 * @param lastEvaluated 
 */


data class FlowInfo (

    @SerializedName("uuid")
    val uuid: kotlin.String? = null,

    @SerializedName("owner")
    val owner: AccountInfo? = null,

    @SerializedName("created")
    val created: kotlin.String? = null,

    @SerializedName("stages")
    val stages: kotlin.collections.List<FlowStageInfo>? = null,

    @SerializedName("last_evaluated")
    val lastEvaluated: kotlin.String? = null

) {


}

