/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.FlowActionInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param condition 
 * @param action 
 */


data class FlowExpressionInfo (

    @SerializedName("condition")
    val condition: kotlin.String? = null,

    @SerializedName("action")
    val action: FlowActionInfo? = null

) {


}

