/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name The name of the action. Which actions are supported depends on the flow service implementation.
 * @param parameters Parameters for the action as list of strings. Which parameters are supported and their format depends on the flow service implementation.
 */


data class FlowActionInfo (

    /* The name of the action. Which actions are supported depends on the flow service implementation. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Parameters for the action as list of strings. Which parameters are supported and their format depends on the flow service implementation. */
    @SerializedName("parameters")
    val parameters: kotlin.collections.List<kotlin.String>? = null

) {


}

