/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name The name of the action.
 * @param parametersPlaceholder Placeholder text shown for the action's parameters in the UI.
 */


data class FlowActionTypeInfo (

    /* The name of the action. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Placeholder text shown for the action's parameters in the UI. */
    @SerializedName("parameters_placeholder")
    val parametersPlaceholder: kotlin.String? = null

) {


}

