/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.FlowExpressionInfo
import com.google.gerrit.client.model.FlowStageState

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param expression The expression defining the condition and the action of this stage as a FlowExpressionInfo entity.
 * @param state The state for this stage. Can be PENDING (the condition of the stage is not satisfied yet or the action has not been executed yet), DONE (the condition of the stage is satisfied and the action has been executed), FAILED (the stage has a non-recoverable error, e.g.
 * @param message Optional message for the stage.
 */


data class FlowStageInfo (

    /* The expression defining the condition and the action of this stage as a FlowExpressionInfo entity. */
    @SerializedName("expression")
    val expression: FlowExpressionInfo? = null,

    /* The state for this stage. Can be PENDING (the condition of the stage is not satisfied yet or the action has not been executed yet), DONE (the condition of the stage is satisfied and the action has been executed), FAILED (the stage has a non-recoverable error, e.g. */
    @SerializedName("state")
    val state: FlowStageState? = null,

    /* Optional message for the stage. */
    @SerializedName("message")
    val message: kotlin.String? = null

) {


}

