/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param showProgress Whether progress information should be shown.
 * @param aggressive Whether an aggressive garbage collection should be done.
 * @param async Whether the garbage collection should run asynchronously.
 */


data class GarbageCollectInput (

    /* Whether progress information should be shown. */
    @SerializedName("show_progress")
    val showProgress: kotlin.Boolean? = null,

    /* Whether an aggressive garbage collection should be done. */
    @SerializedName("aggressive")
    val aggressive: kotlin.Boolean? = null,

    /* Whether the garbage collection should run asynchronously. */
    @SerializedName("async")
    val async: kotlin.Boolean? = null

) {


}

