/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.DateFormat
import com.google.gerrit.client.model.DefaultBase
import com.google.gerrit.client.model.DiffView
import com.google.gerrit.client.model.EmailFormat
import com.google.gerrit.client.model.EmailStrategy
import com.google.gerrit.client.model.MenuItem
import com.google.gerrit.client.model.Theme
import com.google.gerrit.client.model.TimeFormat

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param changesPerPage 
 * @param downloadScheme 
 * @param theme 
 * @param dateFormat 
 * @param timeFormat 
 * @param expandInlineDiffs 
 * @param relativeDateInChangeTable 
 * @param diffView 
 * @param sizeBarInChangeTable 
 * @param legacycidInChangeTable 
 * @param muteCommonPathPrefixes 
 * @param signedOffBy 
 * @param emailStrategy 
 * @param emailFormat 
 * @param defaultBaseForMerges 
 * @param publishCommentsOnPush 
 * @param disableKeyboardShortcuts 
 * @param disableTokenHighlighting 
 * @param workInProgressByDefault 
 * @param my 
 * @param changeTable 
 * @param allowBrowserNotifications 
 * @param allowSuggestCodeWhileCommenting 
 * @param allowAutocompletingComments 
 * @param aiChatSelectedModel 
 * @param labelFilter 
 * @param diffPageSidebar 
 */


data class GeneralPreferencesInfo (

    @SerializedName("changes_per_page")
    val changesPerPage: kotlin.Int? = null,

    @SerializedName("download_scheme")
    val downloadScheme: kotlin.String? = null,

    @SerializedName("theme")
    val theme: Theme? = null,

    @SerializedName("date_format")
    val dateFormat: DateFormat? = null,

    @SerializedName("time_format")
    val timeFormat: TimeFormat? = null,

    @SerializedName("expand_inline_diffs")
    val expandInlineDiffs: kotlin.Boolean? = null,

    @SerializedName("relative_date_in_change_table")
    val relativeDateInChangeTable: kotlin.Boolean? = null,

    @SerializedName("diff_view")
    val diffView: DiffView? = null,

    @SerializedName("size_bar_in_change_table")
    val sizeBarInChangeTable: kotlin.Boolean? = null,

    @SerializedName("legacycid_in_change_table")
    val legacycidInChangeTable: kotlin.Boolean? = null,

    @SerializedName("mute_common_path_prefixes")
    val muteCommonPathPrefixes: kotlin.Boolean? = null,

    @SerializedName("signed_off_by")
    val signedOffBy: kotlin.Boolean? = null,

    @SerializedName("email_strategy")
    val emailStrategy: EmailStrategy? = null,

    @SerializedName("email_format")
    val emailFormat: EmailFormat? = null,

    @SerializedName("default_base_for_merges")
    val defaultBaseForMerges: DefaultBase? = null,

    @SerializedName("publish_comments_on_push")
    val publishCommentsOnPush: kotlin.Boolean? = null,

    @SerializedName("disable_keyboard_shortcuts")
    val disableKeyboardShortcuts: kotlin.Boolean? = null,

    @SerializedName("disable_token_highlighting")
    val disableTokenHighlighting: kotlin.Boolean? = null,

    @SerializedName("work_in_progress_by_default")
    val workInProgressByDefault: kotlin.Boolean? = null,

    @SerializedName("my")
    val my: kotlin.collections.List<MenuItem>? = null,

    @SerializedName("change_table")
    val changeTable: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("allow_browser_notifications")
    val allowBrowserNotifications: kotlin.Boolean? = null,

    @SerializedName("allow_suggest_code_while_commenting")
    val allowSuggestCodeWhileCommenting: kotlin.Boolean? = null,

    @SerializedName("allow_autocompleting_comments")
    val allowAutocompletingComments: kotlin.Boolean? = null,

    @SerializedName("ai_chat_selected_model")
    val aiChatSelectedModel: kotlin.String? = null,

    @SerializedName("label_filter")
    val labelFilter: kotlin.String? = null,

    @SerializedName("diff_page_sidebar")
    val diffPageSidebar: kotlin.String? = null

) {


}

