/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param allProjects The name of the All-Projects root project.
 * @param allUsers The name of the All-Users project, in which per-user data such as account preferences and watched projects is stored.
 * @param docSearch Whether documentation search is available.
 * @param docUrl Custom base URL where Gerrit server documentation is located. (Documentation may still be available at /Documentation relative to the Gerrit base path even if this value is unset.)
 * @param editGpgKeys Whether to enable the web UI for editing GPG keys.
 * @param reportBugUrl URL to report bugs.
 * @param primaryWeblinkName The name of the configured primary web link (gerrit.primaryWeblinkName), if one is set.
 * @param instanceId Short identifier for this Gerrit installation.
 * @param defaultBranch Name of the default branch to use on the project creation.
 * @param projectStatePredicateEnabled Whether the instance supports filtering projects by state.
 */


data class GerritInfo (

    /* The name of the All-Projects root project. */
    @SerializedName("all_projects")
    val allProjects: kotlin.String? = null,

    /* The name of the All-Users project, in which per-user data such as account preferences and watched projects is stored. */
    @SerializedName("all_users")
    val allUsers: kotlin.String? = null,

    /* Whether documentation search is available. */
    @SerializedName("doc_search")
    val docSearch: kotlin.Boolean? = null,

    /* Custom base URL where Gerrit server documentation is located. (Documentation may still be available at /Documentation relative to the Gerrit base path even if this value is unset.) */
    @SerializedName("doc_url")
    val docUrl: kotlin.String? = null,

    /* Whether to enable the web UI for editing GPG keys. */
    @SerializedName("edit_gpg_keys")
    val editGpgKeys: kotlin.Boolean? = null,

    /* URL to report bugs. */
    @SerializedName("report_bug_url")
    val reportBugUrl: kotlin.String? = null,

    /* The name of the configured primary web link (gerrit.primaryWeblinkName), if one is set. */
    @SerializedName("primary_weblink_name")
    val primaryWeblinkName: kotlin.String? = null,

    /* Short identifier for this Gerrit installation. */
    @SerializedName("instance_id")
    val instanceId: kotlin.String? = null,

    /* Name of the default branch to use on the project creation. */
    @SerializedName("default_branch")
    val defaultBranch: kotlin.String? = null,

    /* Whether the instance supports filtering projects by state. */
    @SerializedName("project_state_predicate_enabled")
    val projectStatePredicateEnabled: kotlin.Boolean? = null

) {


}

