/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param visibleToAll Whether the group is visible to all registered users.
 */


data class GroupOptionsInfo (

    /* Whether the group is visible to all registered users. */
    @SerializedName("visible_to_all")
    val visibleToAll: kotlin.Boolean? = null

) {


}

