/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param url URL to the plugin jar.
 * @param raw The raw plugin content (the plugin jar) uploaded in the request body, as an alternative to url.
 */


data class InstallPluginInput (

    /* URL to the plugin jar. */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* The raw plugin content (the plugin jar) uploaded in the request body, as an alternative to url. */
    @SerializedName("raw")
    val raw: kotlin.Any? = null

) {


}

