/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param propertyValues Map of the available values to their description.
 * @param defaultValue The default value of this label.
 */


data class LabelTypeInfo (

    /* Map of the available values to their description. */
    @SerializedName("values")
    val propertyValues: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* The default value of this label. */
    @SerializedName("default_value")
    val defaultValue: kotlin.Int? = null

) {


}

