/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param total 
 * @param used 
 * @param free 
 * @param buffers 
 * @param max 
 * @param openFiles 
 */


data class MemSummaryInfo (

    @SerializedName("total")
    val total: kotlin.String? = null,

    @SerializedName("used")
    val used: kotlin.String? = null,

    @SerializedName("free")
    val free: kotlin.String? = null,

    @SerializedName("buffers")
    val buffers: kotlin.String? = null,

    @SerializedName("max")
    val max: kotlin.String? = null,

    @SerializedName("open_files")
    val openFiles: kotlin.Int? = null

) {


}

