/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.MenuItem

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name Name of the top menu entry.
 * @param items List of menu items.
 */


data class MenuEntry (

    /* Name of the top menu entry. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* List of menu items. */
    @SerializedName("items")
    val items: kotlin.collections.List<MenuItem>? = null

) {


}

