/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInput
import com.google.gerrit.client.model.MergeInput

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param subject 
 * @param inheritParent 
 * @param baseChange 
 * @param merge 
 * @param author 
 * @param validationOptions 
 */


data class MergePatchSetInput (

    @SerializedName("subject")
    val subject: kotlin.String? = null,

    @SerializedName("inherit_parent")
    val inheritParent: kotlin.Boolean? = null,

    @SerializedName("base_change")
    val baseChange: kotlin.String? = null,

    @SerializedName("merge")
    val merge: MergeInput? = null,

    @SerializedName("author")
    val author: AccountInput? = null,

    @SerializedName("validation_options")
    val validationOptions: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

