/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInput
import com.google.gerrit.client.model.MergeInput

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param subject The new subject for the change, if not specified, will reuse the current patch set's subject
 * @param inheritParent Use the current patch set's first parent as the merge tip when set to true.
 * @param baseChange A \\{change-id\\} that identifies a change. When inherit_parent is false, the merge tip will be the current patch set of the base_change if it's set. Otherwise, the current branch tip of the destination branch will be used.
 * @param merge The detail of the source commit for merge as a MergeInput entity.
 * @param author The author of the commit to create. Must be an AccountInput entity with at least the name and email fields set. The caller needs \"Forge Author\" permission when using this field. This field does not affect the owner or the committer of the change, which will continue to use the identity of the caller.
 * @param validationOptions Map with key-value pairs that are forwarded as options to the commit validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed commit validation listeners.
 */


data class MergePatchSetInput (

    /* The new subject for the change, if not specified, will reuse the current patch set's subject */
    @SerializedName("subject")
    val subject: kotlin.String? = null,

    /* Use the current patch set's first parent as the merge tip when set to true. */
    @SerializedName("inherit_parent")
    val inheritParent: kotlin.Boolean? = null,

    /* A \\{change-id\\} that identifies a change. When inherit_parent is false, the merge tip will be the current patch set of the base_change if it's set. Otherwise, the current branch tip of the destination branch will be used. */
    @SerializedName("base_change")
    val baseChange: kotlin.String? = null,

    /* The detail of the source commit for merge as a MergeInput entity. */
    @SerializedName("merge")
    val merge: MergeInput? = null,

    /* The author of the commit to create. Must be an AccountInput entity with at least the name and email fields set. The caller needs \"Forge Author\" permission when using this field. This field does not affect the owner or the committer of the change, which will continue to use the identity of the caller. */
    @SerializedName("author")
    val author: AccountInput? = null,

    /* Map with key-value pairs that are forwarded as options to the commit validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed commit validation listeners. */
    @SerializedName("validation_options")
    val validationOptions: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

