/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param parent The name of the parent project.
 * @param commitMessage Message that should be used to commit the change of the project parent in the project.config file to the refs/meta/config branch.
 */


data class ParentInput (

    /* The name of the parent project. */
    @SerializedName("parent")
    val parent: kotlin.String? = null,

    /* Message that should be used to commit the change of the project parent in the project.config file to the refs/meta/config branch. */
    @SerializedName("commit_message")
    val commitMessage: kotlin.String? = null

) {


}

