/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name The name of the plugin that contributed the information.
 * @param message A message from the plugin.
 */


data class PluginDefinedInfo (

    /* The name of the plugin that contributed the information. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* A message from the plugin. */
    @SerializedName("message")
    val message: kotlin.String? = null

) {


}

