/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id The ID of the plugin.
 * @param version The version of the plugin.
 * @param apiVersion The version of the Gerrit Api used by the plugin.
 * @param indexUrl URL of the plugin's default page.
 * @param filename The plugin's filename.
 * @param disabled Whether the plugin is disabled.
 */


data class PluginInfo (

    /* The ID of the plugin. */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* The version of the plugin. */
    @SerializedName("version")
    val version: kotlin.String? = null,

    /* The version of the Gerrit Api used by the plugin. */
    @SerializedName("api_version")
    val apiVersion: kotlin.String? = null,

    /* URL of the plugin's default page. */
    @SerializedName("index_url")
    val indexUrl: kotlin.String? = null,

    /* The plugin's filename. */
    @SerializedName("filename")
    val filename: kotlin.String? = null,

    /* Whether the plugin is disabled. */
    @SerializedName("disabled")
    val disabled: kotlin.Boolean? = null

) {


}

