/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.Operation

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param operation 
 * @param caches 
 */


data class PostCachesInput (

    @SerializedName("operation")
    val operation: Operation? = null,

    @SerializedName("caches")
    val caches: kotlin.collections.List<kotlin.String>? = null

) {


}

