/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.ProblemInfoStatus

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param message 
 * @param status 
 * @param outcome 
 */


data class ProblemInfo (

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("status")
    val status: ProblemInfoStatus? = null,

    @SerializedName("outcome")
    val outcome: kotlin.String? = null

) {


}

