/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccessSectionInfo
import com.google.gerrit.client.model.GroupInfo
import com.google.gerrit.client.model.ProjectInfo
import com.google.gerrit.client.model.WebLinkInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param revision 
 * @param inheritsFrom 
 * @param local 
 * @param isOwner 
 * @param ownerOf 
 * @param canUpload 
 * @param canAdd 
 * @param canAddTags 
 * @param configVisible 
 * @param requireChangeForConfigUpdate 
 * @param groups 
 * @param configWebLinks 
 */


data class ProjectAccessInfo (

    @SerializedName("revision")
    val revision: kotlin.String? = null,

    @SerializedName("inherits_from")
    val inheritsFrom: ProjectInfo? = null,

    @SerializedName("local")
    val local: kotlin.collections.Map<kotlin.String, AccessSectionInfo>? = null,

    @SerializedName("is_owner")
    val isOwner: kotlin.Boolean? = null,

    @SerializedName("owner_of")
    val ownerOf: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("can_upload")
    val canUpload: kotlin.Boolean? = null,

    @SerializedName("can_add")
    val canAdd: kotlin.Boolean? = null,

    @SerializedName("can_add_tags")
    val canAddTags: kotlin.Boolean? = null,

    @SerializedName("config_visible")
    val configVisible: kotlin.Boolean? = null,

    @SerializedName("require_change_for_config_update")
    val requireChangeForConfigUpdate: kotlin.Boolean? = null,

    @SerializedName("groups")
    val groups: kotlin.collections.Map<kotlin.String, GroupInfo>? = null,

    @SerializedName("config_web_links")
    val configWebLinks: kotlin.collections.List<WebLinkInfo>? = null

) {


}

