/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.NotifyHandling
import com.google.gerrit.client.model.NotifyInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param notify Notify handling that defines to whom email notifications should be sent after the change edit is published. + Allowed values are NONE and ALL. + If not set, the default is ALL.
 * @param notifyDetails Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
 */


data class PublishChangeEditInput (

    /* Notify handling that defines to whom email notifications should be sent after the change edit is published. + Allowed values are NONE and ALL. + If not set, the default is ALL. */
    @SerializedName("notify")
    val notify: NotifyHandling? = null,

    /* Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity. */
    @SerializedName("notify_details")
    val notifyDetails: kotlin.collections.Map<kotlin.String, NotifyInfo>? = null

) {


}

