/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param base 
 * @param strategy 
 * @param allowConflicts 
 * @param onBehalfOfUploader 
 * @param validationOptions 
 * @param committerEmail 
 */


data class RebaseInput (

    @SerializedName("base")
    val base: kotlin.String? = null,

    @SerializedName("strategy")
    val strategy: kotlin.String? = null,

    @SerializedName("allow_conflicts")
    val allowConflicts: kotlin.Boolean? = null,

    @SerializedName("on_behalf_of_uploader")
    val onBehalfOfUploader: kotlin.Boolean? = null,

    @SerializedName("validation_options")
    val validationOptions: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerializedName("committer_email")
    val committerEmail: kotlin.String? = null

) {


}

