/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param reuse Whether existing documents may be reused instead of being recomputed while reindexing.
 * @param notifyListeners Whether index listeners should be notified about the reindex progress.
 */


data class ReindexIndexVersionInput (

    /* Whether existing documents may be reused instead of being recomputed while reindexing. */
    @SerializedName("reuse")
    val reuse: kotlin.Boolean? = null,

    /* Whether index listeners should be notified about the reindex progress. */
    @SerializedName("notify_listeners")
    val notifyListeners: kotlin.Boolean? = null

) {


}

