/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.ChangeInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param revertChanges A list of ChangeInfo that describes the revert changes. Each entity in that list is a revert change that was created in that revert submission.
 */


data class RevertSubmissionInfo (

    /* A list of ChangeInfo that describes the revert changes. Each entity in that list is a revert change that was created in that revert submission. */
    @SerializedName("revert_changes")
    val revertChanges: kotlin.collections.List<ChangeInfo>? = null

) {


}

