/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AvatarInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param approvals The approvals of the reviewer as a map that maps the label names to the approval values (\"-2\", \"-1\", \"0\", \"+1\", \"+2\").
 * @param accountId This field is inherited from AccountInfo but is optional here if an unregistered reviewer was added by email. See add-reviewer for details.
 * @param name 
 * @param displayName 
 * @param email 
 * @param secondaryEmails 
 * @param username 
 * @param avatars 
 * @param moreAccounts 
 * @param status 
 * @param inactive 
 * @param deleted 
 * @param tags 
 */


data class ReviewerInfo (

    /* The approvals of the reviewer as a map that maps the label names to the approval values (\"-2\", \"-1\", \"0\", \"+1\", \"+2\"). */
    @SerializedName("approvals")
    val approvals: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* This field is inherited from AccountInfo but is optional here if an unregistered reviewer was added by email. See add-reviewer for details. */
    @SerializedName("_account_id")
    val accountId: kotlin.Int? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("display_name")
    val displayName: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("secondary_emails")
    val secondaryEmails: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("avatars")
    val avatars: kotlin.collections.List<AvatarInfo>? = null,

    @SerializedName("_more_accounts")
    val moreAccounts: kotlin.Boolean? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("inactive")
    val inactive: kotlin.Boolean? = null,

    @SerializedName("deleted")
    val deleted: kotlin.Boolean? = null,

    @SerializedName("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

