/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.ActionInfo
import com.google.gerrit.client.model.ChangeKind
import com.google.gerrit.client.model.CommitInfo
import com.google.gerrit.client.model.CommonFileInfo
import com.google.gerrit.client.model.ConflictsInfo
import com.google.gerrit.client.model.FetchInfo
import com.google.gerrit.client.model.ParentInfo
import com.google.gerrit.client.model.PushCertificateInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param kind 
 * @param number 
 * @param created 
 * @param uploader 
 * @param realUploader 
 * @param ref 
 * @param fetch 
 * @param commit 
 * @param parentsData 
 * @param branch 
 * @param files 
 * @param actions 
 * @param commitWithFooters 
 * @param pushCertificate 
 * @param description 
 * @param conflicts 
 */


data class RevisionInfo (

    @SerializedName("kind")
    val kind: ChangeKind? = null,

    @SerializedName("_number")
    val number: kotlin.Int? = null,

    @SerializedName("created")
    val created: kotlin.String? = null,

    @SerializedName("uploader")
    val uploader: AccountInfo? = null,

    @SerializedName("real_uploader")
    val realUploader: AccountInfo? = null,

    @SerializedName("ref")
    val ref: kotlin.String? = null,

    @SerializedName("fetch")
    val fetch: kotlin.collections.Map<kotlin.String, FetchInfo>? = null,

    @SerializedName("commit")
    val commit: CommitInfo? = null,

    @SerializedName("parents_data")
    val parentsData: kotlin.collections.List<ParentInfo>? = null,

    @SerializedName("branch")
    val branch: kotlin.String? = null,

    @SerializedName("files")
    val files: kotlin.collections.Map<kotlin.String, CommonFileInfo>? = null,

    @SerializedName("actions")
    val actions: kotlin.collections.Map<kotlin.String, ActionInfo>? = null,

    @SerializedName("commit_with_footers")
    val commitWithFooters: kotlin.String? = null,

    @SerializedName("push_certificate")
    val pushCertificate: PushCertificateInfo? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("conflicts")
    val conflicts: ConflictsInfo? = null

) {


}

