/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.ReviewerState

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param updated 
 * @param updatedBy 
 * @param realUpdatedBy 
 * @param reviewer 
 * @param state 
 */


data class ReviewerUpdateInfo (

    @SerializedName("updated")
    val updated: kotlin.String? = null,

    @SerializedName("updated_by")
    val updatedBy: AccountInfo? = null,

    @SerializedName("real_updated_by")
    val realUpdatedBy: AccountInfo? = null,

    @SerializedName("reviewer")
    val reviewer: AccountInfo? = null,

    @SerializedName("state")
    val state: ReviewerState? = null

) {


}

