/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountInfo
import com.google.gerrit.client.model.ContextLineInfo
import com.google.gerrit.client.model.FixSuggestionInfo
import com.google.gerrit.client.model.Range
import com.google.gerrit.client.model.Side

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param author 
 * @param tag 
 * @param changeMessageId 
 * @param unresolved 
 * @param contextLines 
 * @param sourceContentType 
 * @param patchSet 
 * @param id 
 * @param path 
 * @param side 
 * @param parent 
 * @param line 
 * @param range 
 * @param inReplyTo 
 * @param updated 
 * @param message 
 * @param commitId 
 * @param fixSuggestions 
 * @param isAi 
 */


data class RobotCommentInfo (

    @SerializedName("author")
    val author: AccountInfo? = null,

    @SerializedName("tag")
    val tag: kotlin.String? = null,

    @SerializedName("change_message_id")
    val changeMessageId: kotlin.String? = null,

    @SerializedName("unresolved")
    val unresolved: kotlin.Boolean? = null,

    @SerializedName("context_lines")
    val contextLines: kotlin.collections.List<ContextLineInfo>? = null,

    @SerializedName("source_content_type")
    val sourceContentType: kotlin.String? = null,

    @SerializedName("patch_set")
    val patchSet: kotlin.Int? = null,

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("path")
    val path: kotlin.String? = null,

    @SerializedName("side")
    val side: Side? = null,

    @SerializedName("parent")
    val parent: kotlin.Int? = null,

    @SerializedName("line")
    val line: kotlin.Int? = null,

    @SerializedName("range")
    val range: Range? = null,

    @SerializedName("in_reply_to")
    val inReplyTo: kotlin.String? = null,

    @SerializedName("updated")
    val updated: kotlin.String? = null,

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("commit_id")
    val commitId: kotlin.String? = null,

    @SerializedName("fix_suggestions")
    val fixSuggestions: kotlin.collections.List<FixSuggestionInfo>? = null,

    @SerializedName("is_ai")
    val isAi: kotlin.Boolean? = null

) {


}

