/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.AccountsInfo
import com.google.gerrit.client.model.AuthInfo
import com.google.gerrit.client.model.ChangeConfigInfo
import com.google.gerrit.client.model.DownloadInfo
import com.google.gerrit.client.model.GerritInfo
import com.google.gerrit.client.model.GroupsInfo
import com.google.gerrit.client.model.MetadataInfo
import com.google.gerrit.client.model.PluginConfigInfo
import com.google.gerrit.client.model.ReceiveInfo
import com.google.gerrit.client.model.SuggestInfo
import com.google.gerrit.client.model.UserConfigInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accounts 
 * @param auth 
 * @param change 
 * @param download 
 * @param gerrit 
 * @param groups 
 * @param noteDbEnabled 
 * @param plugin 
 * @param sshd 
 * @param suggest 
 * @param user 
 * @param receive 
 * @param defaultTheme 
 * @param submitRequirementDashboardColumns 
 * @param dashboardShowAllLabels 
 * @param metadata 
 */


data class ServerInfo (

    @SerializedName("accounts")
    val accounts: AccountsInfo? = null,

    @SerializedName("auth")
    val auth: AuthInfo? = null,

    @SerializedName("change")
    val change: ChangeConfigInfo? = null,

    @SerializedName("download")
    val download: DownloadInfo? = null,

    @SerializedName("gerrit")
    val gerrit: GerritInfo? = null,

    @SerializedName("groups")
    val groups: GroupsInfo? = null,

    @SerializedName("note_db_enabled")
    val noteDbEnabled: kotlin.Boolean? = null,

    @SerializedName("plugin")
    val plugin: PluginConfigInfo? = null,

    @SerializedName("sshd")
    val sshd: kotlin.Any? = null,

    @SerializedName("suggest")
    val suggest: SuggestInfo? = null,

    @SerializedName("user")
    val user: UserConfigInfo? = null,

    @SerializedName("receive")
    val receive: ReceiveInfo? = null,

    @SerializedName("default_theme")
    val defaultTheme: kotlin.String? = null,

    @SerializedName("submit_requirement_dashboard_columns")
    val submitRequirementDashboardColumns: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("dashboard_show_all_labels")
    val dashboardShowAllLabels: kotlin.Boolean? = null,

    @SerializedName("metadata")
    val metadata: kotlin.collections.List<MetadataInfo>? = null

) {


}

