/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param seq 
 * @param sshPublicKey 
 * @param encodedKey 
 * @param algorithm 
 * @param comment 
 * @param valid 
 */


data class SshKeyInfo (

    @SerializedName("seq")
    val seq: kotlin.Int? = null,

    @SerializedName("ssh_public_key")
    val sshPublicKey: kotlin.String? = null,

    @SerializedName("encoded_key")
    val encodedKey: kotlin.String? = null,

    @SerializedName("algorithm")
    val algorithm: kotlin.String? = null,

    @SerializedName("comment")
    val comment: kotlin.String? = null,

    @SerializedName("valid")
    val valid: kotlin.Boolean? = null

) {


}

