/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: DONE,CANCELLED,STOPPING,RUNNING,STARTING,PARKED,READY,SLEEPING,OTHER
 */

enum class State(val value: kotlin.String) {

    @SerializedName(value = "DONE")
    DONE("DONE"),

    @SerializedName(value = "CANCELLED")
    CANCELLED("CANCELLED"),

    @SerializedName(value = "STOPPING")
    STOPPING("STOPPING"),

    @SerializedName(value = "RUNNING")
    RUNNING("RUNNING"),

    @SerializedName(value = "STARTING")
    STARTING("STARTING"),

    @SerializedName(value = "PARKED")
    PARKED("PARKED"),

    @SerializedName(value = "READY")
    READY("READY"),

    @SerializedName(value = "SLEEPING")
    SLEEPING("SLEEPING"),

    @SerializedName(value = "OTHER")
    OTHER("OTHER");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is State) "$data" else null

        /**
         * Returns a valid [State] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): State? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

