/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.SubmitType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `value` The effective submit type value. Never INHERIT.
 * @param configuredValue The configured value, can be one of the submit types, or INHERIT to inherit from the parent project.
 * @param inheritedValue The effective value that would be inherited from the parent. Never INHERIT.
 */


data class SubmitTypeInfo (

    /* The effective submit type value. Never INHERIT. */
    @SerializedName("value")
    val `value`: SubmitType? = null,

    /* The configured value, can be one of the submit types, or INHERIT to inherit from the parent project. */
    @SerializedName("configured_value")
    val configuredValue: SubmitType? = null,

    /* The effective value that would be inherited from the parent. Never INHERIT. */
    @SerializedName("inherited_value")
    val inheritedValue: SubmitType? = null

) {


}

