/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.SubmitType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `value` 
 * @param configuredValue 
 * @param inheritedValue 
 */


data class SubmitTypeInfo (

    @SerializedName("value")
    val `value`: SubmitType? = null,

    @SerializedName("configured_value")
    val configuredValue: SubmitType? = null,

    @SerializedName("inherited_value")
    val inheritedValue: SubmitType? = null

) {


}

