/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: INHERIT,FAST_FORWARD_ONLY,MERGE_IF_NECESSARY,REBASE_IF_NECESSARY,REBASE_ALWAYS,MERGE_ALWAYS,CHERRY_PICK
 */

enum class SubmitType(val value: kotlin.String) {

    @SerializedName(value = "INHERIT")
    INHERIT("INHERIT"),

    @SerializedName(value = "FAST_FORWARD_ONLY")
    FAST_FORWARD_ONLY("FAST_FORWARD_ONLY"),

    @SerializedName(value = "MERGE_IF_NECESSARY")
    MERGE_IF_NECESSARY("MERGE_IF_NECESSARY"),

    @SerializedName(value = "REBASE_IF_NECESSARY")
    REBASE_IF_NECESSARY("REBASE_IF_NECESSARY"),

    @SerializedName(value = "REBASE_ALWAYS")
    REBASE_ALWAYS("REBASE_ALWAYS"),

    @SerializedName(value = "MERGE_ALWAYS")
    MERGE_ALWAYS("MERGE_ALWAYS"),

    @SerializedName(value = "CHERRY_PICK")
    CHERRY_PICK("CHERRY_PICK");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubmitType) "$data" else null

        /**
         * Returns a valid [SubmitType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubmitType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

