/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.JvmSummaryInfo
import com.google.gerrit.client.model.MemSummaryInfo
import com.google.gerrit.client.model.TaskSummaryInfo
import com.google.gerrit.client.model.ThreadSummaryInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param taskSummary 
 * @param memSummary 
 * @param threadSummary 
 * @param jvmSummary 
 */


data class SummaryInfo (

    @SerializedName("task_summary")
    val taskSummary: TaskSummaryInfo? = null,

    @SerializedName("mem_summary")
    val memSummary: MemSummaryInfo? = null,

    @SerializedName("thread_summary")
    val threadSummary: ThreadSummaryInfo? = null,

    @SerializedName("jvm_summary")
    val jvmSummary: JvmSummaryInfo? = null

) {


}

