/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.GitPerson
import com.google.gerrit.client.model.WebLinkInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `object` 
 * @param message 
 * @param tagger 
 * @param created 
 * @param webLinks 
 * @param ref 
 * @param revision 
 * @param canDelete 
 */


data class TagInfo (

    @SerializedName("object")
    val `object`: kotlin.String? = null,

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("tagger")
    val tagger: GitPerson? = null,

    @SerializedName("created")
    val created: kotlin.String? = null,

    @SerializedName("web_links")
    val webLinks: kotlin.collections.List<WebLinkInfo>? = null,

    @SerializedName("ref")
    val ref: kotlin.String? = null,

    @SerializedName("revision")
    val revision: kotlin.String? = null,

    @SerializedName("can_delete")
    val canDelete: kotlin.Boolean? = null

) {


}

