/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param total 
 * @param stopping 
 * @param running 
 * @param parked 
 * @param starting 
 * @param ready 
 * @param sleeping 
 */


data class TaskSummaryInfo (

    @SerializedName("total")
    val total: kotlin.Int? = null,

    @SerializedName("stopping")
    val stopping: kotlin.Int? = null,

    @SerializedName("running")
    val running: kotlin.Int? = null,

    @SerializedName("parked")
    val parked: kotlin.Int? = null,

    @SerializedName("starting")
    val starting: kotlin.Int? = null,

    @SerializedName("ready")
    val ready: kotlin.Int? = null,

    @SerializedName("sleeping")
    val sleeping: kotlin.Int? = null

) {


}

