/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param anonymousCowardName Username that is displayed in the Gerrit Web UI and in e-mail notifications if the full name of the user is not set.
 */


data class UserConfigInfo (

    /* Username that is displayed in the Gerrit Web UI and in e-mail notifications if the full name of the user is not set. */
    @SerializedName("anonymous_coward_name")
    val anonymousCowardName: kotlin.String? = null

) {


}

