/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.google.gerrit.client.model

import com.google.gerrit.client.model.ValidationOptionInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param validationOptions The list of all possible validation options.
 */


data class ValidationOptionInfos (

    /* The list of all possible validation options. */
    @SerializedName("validation_options")
    val validationOptions: kotlin.collections.List<ValidationOptionInfo>? = null

) {


}

